// User actions: every state mutation the UI triggers (toggles, add/edit/delete
// modals, scenes, notifications, search). Alerts are escaped where rendered.
import {
  S, esc, val, money, fd, ds, nextDue, gm, cu, ia, CY, CM, CD,
  showToast, showModal, hideModal
} from './core.js';
import { catColors, incCats, expCats, dayNames, debtMeta, devTypeMeta, deviceIcons, roomIcons } from './constants.js';
import { roomOpts, iconOpts } from './components.js';
import { render, renderNav } from './views.js';
import { persist } from './api.js';
import { runAutomations } from './automations.js';

export function typeOpts(sel) { return ['light', 'lock', 'camera', 'sensor', 'media', 'appliance', 'climate'].map(function (t) { return '<option value="' + t + '"' + (t === sel ? ' selected' : '') + '>' + devTypeMeta[t].label + '</option>'; }).join(''); }

/* ===== Finance: transactions ===== */
export function deleteTx(id) { S.transactions = S.transactions.filter(function (t) { return t.id !== id; }); render(); showToast('Transaction deleted', 'warning'); }
var txType = 'income';
export function openAddTransaction() { txType = 'income'; showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Transaction</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Type</label><div class="grid grid-cols-2 gap-3"><button class="btn btn-sm" id="tx-inc" onclick="setTxType(\'income\')" style="background:rgba(16,185,129,.15);color:var(--accent);border:1px solid var(--accent)"><i class="fa-solid fa-arrow-down"></i>Income</button><button class="btn btn-sm" id="tx-exp" onclick="setTxType(\'expense\')" style="background:var(--surface2);color:var(--muted);border:1px solid var(--border)"><i class="fa-solid fa-arrow-up"></i>Expense</button></div></div><div><label>Category</label><select class="input" id="tx-cat">' + incCats.map(function (c) { return '<option value="' + c + '">' + c + '</option>'; }).join('') + '</select></div><div><label>Amount ($)</label><input class="input" id="tx-amount" type="number" min="0" step="0.01" placeholder="0.00"></div><div><label>Date</label><input class="input" id="tx-date" type="date" value="' + ds() + '"></div><div><label>Member</label><select class="input" id="tx-member">' + S.members.map(function (m) { return '<option value="' + m.id + '" ' + (m.id === S.userId ? 'selected' : '') + '>' + esc(m.name) + '</option>'; }).join('') + '</select></div><div><label>Note</label><input class="input" id="tx-note" placeholder="Brief description"></div><button class="btn btn-primary w-full" onclick="saveTransaction()">Save</button></div></div>'); }
export function setTxType(type) { txType = type; var incBtn = document.getElementById('tx-inc'); var expBtn = document.getElementById('tx-exp'); if (type === 'income') { incBtn.style.background = 'rgba(16,185,129,.15)'; incBtn.style.color = 'var(--accent)'; incBtn.style.borderColor = 'var(--accent)'; expBtn.style.background = 'var(--surface2)'; expBtn.style.color = 'var(--muted)'; expBtn.style.borderColor = 'var(--border)'; } else { expBtn.style.background = 'rgba(239,68,68,.15)'; expBtn.style.color = 'var(--red)'; expBtn.style.borderColor = 'var(--red)'; incBtn.style.background = 'var(--surface2)'; incBtn.style.color = 'var(--muted)'; incBtn.style.borderColor = 'var(--border)'; } document.getElementById('tx-cat').innerHTML = (type === 'income' ? incCats : expCats).map(function (c) { return '<option value="' + c + '">' + c + '</option>'; }).join(''); }
export function saveTransaction() { var amount = parseFloat(document.getElementById('tx-amount').value), date = document.getElementById('tx-date').value, cat = document.getElementById('tx-cat').value, memberId = +document.getElementById('tx-member').value, note = document.getElementById('tx-note').value.trim(); if (!amount || amount <= 0 || !date) { showToast('Fill amount and date', 'error'); return; } S.transactions.push({ id: ++S.nid, type: txType, cat: cat, amount: amount, date: date, memberId: memberId, note: note || cat }); hideModal(); render(); showToast((txType === 'income' ? 'Income' : 'Expense') + ' of $' + amount.toLocaleString() + ' added', 'success'); }

/* ===== Finance: recurring ===== */
export function payRecurring(id) { var r = S.recurring.find(function (x) { return x.id === id; }); if (!r) return; var type = r.kind === 'income' ? 'income' : 'expense'; S.transactions.push({ id: ++S.nid, type: type, cat: r.cat, amount: +r.amount, date: ds(), memberId: r.memberId || S.userId, note: r.name + (type === 'expense' ? ' (bill)' : '') }); r.next = nextDue(r.next, r.freq); S.alerts.unshift({ id: ++S.nid, type: 'budget', msg: r.name + ' ' + (type === 'income' ? 'received' : 'paid') + ' — ' + money(r.amount), time: 'Just now', sev: type === 'income' ? 'success' : 'info', seen: false }); render(); showToast(r.name + ' ' + (type === 'income' ? 'posted' : 'paid') + ' · ' + money(r.amount), 'success'); }
export function deleteRecurring(id) { S.recurring = S.recurring.filter(function (x) { return x.id !== id; }); render(); showToast('Recurring item removed', 'warning'); }
export function rcKindChange() { var kind = val('rc-kind'); var cats = kind === 'income' ? incCats : expCats; var sel = document.getElementById('rc-cat'); if (sel) sel.innerHTML = cats.map(function (c) { return '<option value="' + c + '">' + c + '</option>'; }).join(''); }
export function openAddRecurring() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Recurring</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="rc-name" placeholder="e.g. Rent, Spotify, Salary"></div><div class="grid grid-cols-2 gap-3"><div><label>Type</label><select class="input" id="rc-kind" onchange="rcKindChange()"><option value="bill">Bill / Expense</option><option value="income">Income</option></select></div><div><label>Category</label><select class="input" id="rc-cat">' + expCats.map(function (c) { return '<option value="' + c + '">' + c + '</option>'; }).join('') + '</select></div></div><div class="grid grid-cols-2 gap-3"><div><label>Amount ($)</label><input class="input" id="rc-amount" type="number" min="0" step="0.01" placeholder="0.00"></div><div><label>Frequency</label><select class="input" id="rc-freq"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="yearly">Yearly</option></select></div></div><div class="grid grid-cols-2 gap-3"><div><label>Next due</label><input class="input" id="rc-next" type="date" value="' + ds(7) + '"></div><div><label>Member</label><select class="input" id="rc-member">' + S.members.map(function (m) { return '<option value="' + m.id + '"' + (m.id === S.userId ? ' selected' : '') + '>' + esc(m.name) + '</option>'; }).join('') + '</select></div></div><label class="flex items-center gap-2 cursor-pointer" style="margin-bottom:0"><input type="checkbox" id="rc-auto" style="width:auto"> <span>Auto-pay enabled</span></label><button class="btn btn-primary w-full" onclick="saveRecurring()">Add Recurring</button></div></div>'); }
export function saveRecurring() { var name = val('rc-name').trim(), kind = val('rc-kind'), cat = val('rc-cat'), amount = parseFloat(val('rc-amount')), freq = val('rc-freq'), next = val('rc-next'), memberId = +val('rc-member'), autopay = document.getElementById('rc-auto').checked; if (!name || !amount || amount <= 0 || !next) { showToast('Fill name, amount and date', 'error'); return; } S.recurring.push({ id: ++S.nid, name: name, kind: kind, cat: cat, amount: amount, freq: freq, next: next, memberId: memberId, autopay: autopay }); hideModal(); render(); showToast('Recurring "' + name + '" added', 'success'); }

/* ===== Finance: debts ===== */
export function debtKindChange() { var w = document.getElementById('debt-limit-wrap'); if (w) w.style.display = val('debt-kind') === 'credit_card' ? 'block' : 'none'; }
export function openAddDebt() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Debt</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="debt-name" placeholder="e.g. Visa, Car Loan"></div><div class="grid grid-cols-2 gap-3"><div><label>Type</label><select class="input" id="debt-kind" onchange="debtKindChange()">' + Object.keys(debtMeta).map(function (k) { return '<option value="' + k + '">' + debtMeta[k].label + '</option>'; }).join('') + '</select></div><div><label>Balance ($)</label><input class="input" id="debt-balance" type="number" min="0" step="0.01" placeholder="0.00"></div></div><div class="grid grid-cols-2 gap-3"><div><label>APR (%)</label><input class="input" id="debt-apr" type="number" min="0" step="0.01" placeholder="19.99"></div><div><label>Min payment ($)</label><input class="input" id="debt-min" type="number" min="0" step="0.01" placeholder="50"></div></div><div id="debt-limit-wrap" style="display:none"><label>Credit limit ($)</label><input class="input" id="debt-limit" type="number" min="0" placeholder="8000"></div><div><label>Next due date</label><input class="input" id="debt-due" type="date" value="' + ds(14) + '"></div><button class="btn btn-primary w-full" onclick="saveDebt()">Add Debt</button></div></div>'); }
export function saveDebt() { var name = val('debt-name').trim(), kind = val('debt-kind'), balance = parseFloat(val('debt-balance')), apr = parseFloat(val('debt-apr')) || 0, min = parseFloat(val('debt-min')) || 0, limit = parseFloat(val('debt-limit')) || 0, due = val('debt-due'); if (!name || isNaN(balance)) { showToast('Fill name and balance', 'error'); return; } var d = { id: ++S.nid, name: name, kind: kind, balance: balance, apr: apr, minPayment: min, due: due }; if (kind === 'credit_card' && limit) d.limit = limit; S.debts.push(d); hideModal(); render(); showToast('"' + name + '" added', 'success'); }
export function deleteDebt(id) { S.debts = S.debts.filter(function (x) { return x.id !== id; }); render(); showToast('Debt removed', 'warning'); }
export function openPayDebt(id) { var d = S.debts.find(function (x) { return x.id === id; }); if (!d) return; showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Pay ' + esc(d.name) + '</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div class="flex justify-between text-sm"><span class="text-[var(--muted)]">Current balance</span><span class="font-bold">' + money(d.balance) + '</span></div><div><label>Payment amount ($)</label><input class="input" id="pd-amt" type="number" min="0" step="0.01" value="' + d.minPayment + '"></div><div class="flex gap-2"><button class="btn btn-ghost btn-sm" onclick="document.getElementById(\'pd-amt\').value=' + d.minPayment + '">Min ' + money(d.minPayment) + '</button><button class="btn btn-ghost btn-sm" onclick="document.getElementById(\'pd-amt\').value=' + d.balance + '">Pay off ' + money(d.balance) + '</button></div><div><label>From member</label><select class="input" id="pd-member">' + S.members.map(function (m) { return '<option value="' + m.id + '"' + (m.id === S.userId ? ' selected' : '') + '>' + esc(m.name) + '</option>'; }).join('') + '</select></div><button class="btn btn-primary w-full" onclick="savePayDebt(' + id + ')">Make Payment</button></div></div>'); }
export function savePayDebt(id) { var d = S.debts.find(function (x) { return x.id === id; }); if (!d) return; var amt = parseFloat(val('pd-amt')), mem = +val('pd-member'); if (!amt || amt <= 0) { showToast('Enter a valid amount', 'error'); return; } amt = Math.min(amt, d.balance); d.balance = Math.round((d.balance - amt) * 100) / 100; S.transactions.push({ id: ++S.nid, type: 'expense', cat: 'Debt Payment', amount: amt, date: ds(), memberId: mem, note: 'Payment: ' + d.name }); S.alerts.unshift({ id: ++S.nid, type: 'budget', msg: money(amt) + ' paid toward ' + d.name, time: 'Just now', sev: 'info', seen: false }); hideModal(); render(); if (d.balance <= 0) { showToast(d.name + ' paid off! 🎉', 'success'); } else { showToast(money(amt) + ' paid · ' + money(d.balance) + ' left', 'success'); } }

/* ===== Finance: savings & budgets ===== */
export function addToSavings(id) { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Funds</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Amount ($)</label><input class="input" id="sav-amt" type="number" min="1" placeholder="100"></div><button class="btn btn-primary w-full" onclick="saveSavings(' + id + ')">Add</button></div></div>'); }
export function saveSavings(id) { var amt = parseFloat(document.getElementById('sav-amt').value); if (!amt || amt <= 0) { showToast('Enter a valid amount', 'error'); return; } var s = S.savings.find(function (x) { return x.id === id; }); if (s) s.current = Math.min(s.target, s.current + amt); hideModal(); render(); showToast('$' + amt + ' added', 'success'); }
export function openAddBudget() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Budget</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Category</label><input class="input" id="bud-cat" placeholder="e.g. Dining Out"></div><div><label>Monthly Limit ($)</label><input class="input" id="bud-lim" type="number" placeholder="200"></div><button class="btn btn-primary w-full" onclick="saveBudget()">Add</button></div></div>'); }
export function saveBudget() { var cat = document.getElementById('bud-cat').value.trim(), lim = parseFloat(document.getElementById('bud-lim').value); if (!cat || !lim) { showToast('Fill all fields', 'error'); return; } S.budgets.push({ cat: cat, limit: lim, spent: 0 }); hideModal(); render(); showToast('Budget added', 'success'); }
export function openAddSavings() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">New Savings Goal</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="sav-name" placeholder="e.g. New Laptop"></div><div><label>Target ($)</label><input class="input" id="sav-target" type="number" placeholder="2000"></div><button class="btn btn-primary w-full" onclick="saveNewSavings()">Create</button></div></div>'); }
export function saveNewSavings() { var name = document.getElementById('sav-name').value.trim(), target = parseFloat(document.getElementById('sav-target').value); if (!name || !target) { showToast('Fill all fields', 'error'); return; } S.savings.push({ id: ++S.nid, name: name, target: target, current: 0, icon: 'fa-piggy-bank', color: '#06B6D4' }); hideModal(); render(); showToast('Savings goal created', 'success'); }

/* ===== Smart home: device control ===== */
export function setRoom(r) { S.homeRoom = r; stopCameras(); render(); }
export function toggleLight(id) { var l = S.lights.find(function (x) { return x.id === id; }); if (!l) return; l.on = !l.on; S.alerts.unshift({ id: ++S.nid, type: 'light', msg: l.name + ' turned ' + (l.on ? 'on' : 'off'), time: 'Just now', sev: 'info', seen: false }); render(); showToast(l.name + ' ' + (l.on ? 'on' : 'off'), l.on ? 'success' : 'info'); }
export function setBrightness(id, value) { var l = S.lights.find(function (x) { return x.id === id; }); if (l) l.brightness = value; persist(); }
export function allLights(on) { var rm = S.homeRoom; var ls = rm === 'all' ? S.lights : S.lights.filter(function (l) { return l.room === rm; }); ls.forEach(function (l) { l.on = on; }); render(); showToast('All lights ' + (on ? 'on' : 'off'), on ? 'success' : 'info'); }
export function adjTemp(d) { if (!S.thermostat.on) return; S.thermostat.target = Math.max(55, Math.min(85, S.thermostat.target + d)); render(); }
export function toggleThermo() { S.thermostat.on = !S.thermostat.on; render(); showToast('Climate ' + (S.thermostat.on ? 'on' : 'off'), S.thermostat.on ? 'success' : 'info'); }
export function setThermoMode(m) { S.thermostat.mode = m; S.thermostat.on = true; render(); }
export function toggleArm() { if (!ia()) { showToast('Admin only', 'error'); return; } S.securityArmed = !S.securityArmed; S.alerts.unshift({ id: ++S.nid, type: 'system', msg: 'System ' + (S.securityArmed ? 'armed' : 'disarmed'), time: 'Just now', sev: S.securityArmed ? 'success' : 'warning', seen: false }); runAutomations({ type: 'security', armed: S.securityArmed }); render(); }
export function toggleLock(id) { if (!ia()) { showToast('Admin only', 'error'); return; } var d = S.devices.find(function (x) { return x.id === id; }); if (!d) return; d.status = d.status === 'locked' ? 'unlocked' : 'locked'; d.icon = d.status === 'locked' ? 'fa-lock' : 'fa-lock-open'; S.alerts.unshift({ id: ++S.nid, type: 'door', msg: d.name + ' ' + d.status, time: 'Just now', sev: 'info', seen: false }); render(); }
export function toggleSensor(id) { if (!ia()) { showToast('Admin only', 'error'); return; } var d = S.devices.find(function (x) { return x.id === id; }); if (!d) return; d.status = d.status === 'active' ? 'inactive' : 'active'; render(); }
export function toggleDevice(id) { var d = S.devices.find(function (x) { return x.id === id; }); if (!d) return; if (d.type === 'lock') { toggleLock(id); return; } if (d.type === 'sensor') { toggleSensor(id); return; } d.status = d.status === 'off' ? 'on' : 'off'; S.alerts.unshift({ id: ++S.nid, type: 'device', msg: d.name + ' turned ' + d.status, time: 'Just now', sev: 'info', seen: false }); render(); showToast(d.name + ' ' + d.status, d.status === 'on' ? 'success' : 'info'); }
export function startCameras() { var cams = S.devices.filter(function (d) { return d.type === 'camera' && d.status === 'active'; }); if (!cams.length) return; function draw() { for (var i = 0; i < cams.length; i++) { var cv = document.getElementById('cam-' + cams[i].id); if (!cv) continue; var ctx = cv.getContext('2d'); cv.width = cv.offsetWidth * .8; cv.height = cv.offsetHeight * .8; var w = cv.width, h = cv.height; var img = ctx.createImageData(w, h); for (var j = 0; j < img.data.length; j += 4) { var v = Math.random() * 30 + 15; img.data[j] = v * .3; img.data[j + 1] = v * .85; img.data[j + 2] = v * .3; img.data[j + 3] = 255; } ctx.putImageData(img, 0, 0); ctx.fillStyle = 'rgba(0,0,0,0.12)'; for (var y = 0; y < h; y += 3) ctx.fillRect(0, y, w, 1); var g = ctx.createRadialGradient(w / 2, h / 2, w * .3, w / 2, h / 2, w * .7); g.addColorStop(0, 'rgba(0,0,0,0)'); g.addColorStop(1, 'rgba(0,0,0,0.55)'); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); } document.querySelectorAll('.cam-time').forEach(function (el) { el.textContent = new Date().toLocaleTimeString(); }); S.camAnim = requestAnimationFrame(draw); } draw(); }
export function stopCameras() { if (S.camAnim) { cancelAnimationFrame(S.camAnim); S.camAnim = null; } }

/* ===== Smart home: device & room management ===== */
export function devRoomToggle() { var w = document.getElementById('dev-newroom-wrap'); if (w) w.style.display = val('dev-room') === '__new' ? 'block' : 'none'; }
export function devTypeChange() { var t = val('dev-type'); var sel = document.getElementById('dev-icon'); if (sel && devTypeMeta[t]) sel.value = devTypeMeta[t].icon; var cw = document.getElementById('dev-cam-wrap'); if (cw) cw.style.display = t === 'camera' ? 'block' : 'none'; }
export function openAddDevice() { if (S.rooms.length === 0) { showToast('Add a room first', 'warning'); openAddRoom(); return; } showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Device</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="dev-name" placeholder="e.g. Bedroom Lamp"></div><div class="grid grid-cols-2 gap-3"><div><label>Type</label><select class="input" id="dev-type" onchange="devTypeChange()">' + typeOpts('light') + '</select></div><div><label>Icon</label><select class="input" id="dev-icon">' + iconOpts(deviceIcons, 'fa-lightbulb') + '</select></div></div><div><label>Room</label><select class="input" id="dev-room" onchange="devRoomToggle()">' + roomOpts() + '<option value="__new">+ New room…</option></select></div><div id="dev-newroom-wrap" style="display:none"><div class="grid grid-cols-2 gap-3"><div><label>New room name</label><input class="input" id="dev-newroom" placeholder="e.g. Office"></div><div><label>Room icon</label><select class="input" id="dev-newicon">' + iconOpts(roomIcons, 'fa-couch') + '</select></div></div></div><div id="dev-cam-wrap" style="display:none"><div class="mb-3"><label>Brand</label><input class="input" id="dev-brand" list="cam-brands" placeholder="e.g. Ring, Nest, Arlo, ONVIF"><datalist id="cam-brands"><option>Ring</option><option>Google Nest</option><option>Arlo</option><option>Wyze</option><option>Eufy</option><option>Reolink</option><option>Ubiquiti UniFi</option><option>Hikvision</option><option>Dahua</option><option>TP-Link Tapo</option><option>Blink</option><option>Amcrest</option><option>ONVIF / Generic</option></datalist></div><div class="grid grid-cols-2 gap-3"><div><label>Camera type</label><select class="input" id="dev-camtype"><option value="indoor">Indoor</option><option value="outdoor">Outdoor</option><option value="doorbell">Doorbell</option><option value="ptz">PTZ</option><option value="floodlight">Floodlight</option></select></div><div><label>Stream URL <span class="font-normal text-[var(--muted)]">(optional)</span></label><input class="input" id="dev-stream" placeholder="RTSP / HLS / MJPEG"></div></div></div><button class="btn btn-primary w-full" onclick="saveDevice()">Add Device</button></div></div>'); }
export function saveDevice() { var name = val('dev-name').trim(), type = val('dev-type'), roomSel = val('dev-room'), icon = val('dev-icon'); if (!name) { showToast('Enter a device name', 'error'); return; } var room = roomSel; if (roomSel === '__new') { var rn = val('dev-newroom').trim(); if (!rn) { showToast('Name the new room', 'error'); return; } room = 'room' + (++S.nid); S.rooms.push({ id: room, name: rn, icon: val('dev-newicon') || 'fa-house-chimney' }); } if (!room) room = (S.rooms[0] || {}).id; if (type === 'light') { S.lights.push({ id: ++S.nid, name: name, room: room, on: false, brightness: 80 }); } else { var meta = devTypeMeta[type] || {}; var dv = { id: ++S.nid, name: name, room: room, type: type, status: meta.status || 'off', icon: icon || meta.icon || 'fa-plug' }; if (type === 'camera') { var br = val('dev-brand').trim(); if (br) dv.brand = br; dv.camType = val('dev-camtype') || 'indoor'; var st = val('dev-stream').trim(); if (st) dv.stream = st; } S.devices.push(dv); } S.alerts.unshift({ id: ++S.nid, type: 'device', msg: name + ' added to ' + (S.rooms.find(function (r) { return r.id === room; }) || {}).name, time: 'Just now', sev: 'success', seen: false }); hideModal(); render(); showToast(name + ' added', 'success'); }
export function openManageDevice(kind, id) { var arr = kind === 'light' ? S.lights : S.devices; var d = arr.find(function (x) { return x.id === id; }); if (!d) return; var iconRow = kind === 'light' ? '' : '<div><label>Icon</label><select class="input" id="mng-icon">' + iconOpts(deviceIcons, d.icon) + '</select></div>'; showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Manage Device</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="mng-name" value="' + esc(d.name) + '"></div><div><label>Room</label><select class="input" id="mng-room">' + roomOpts(d.room) + '</select></div>' + iconRow + (d.ip ? '<div class="text-[11px] text-[var(--muted)]"><i class="fa-solid fa-wifi mr-1"></i>' + esc(d.ip) + (d.model ? ' · ' + esc(d.model) : '') + '</div>' : '') + '<div class="flex gap-3 mt-1"><button class="btn btn-primary flex-1" onclick="saveManage(\'' + kind + '\',' + id + ')">Save</button><button class="btn btn-danger flex-1" onclick="removeDevice(\'' + kind + '\',' + id + ')"><i class="fa-solid fa-trash-can"></i>Remove</button></div></div></div>'); }
export function saveManage(kind, id) { var arr = kind === 'light' ? S.lights : S.devices; var d = arr.find(function (x) { return x.id === id; }); if (!d) return; d.name = val('mng-name').trim() || d.name; d.room = val('mng-room') || d.room; if (kind !== 'light') { var ic = val('mng-icon'); if (ic) d.icon = ic; } hideModal(); render(); showToast('Device updated', 'success'); }
export function removeDevice(kind, id) { if (kind === 'light') S.lights = S.lights.filter(function (x) { return x.id !== id; }); else S.devices = S.devices.filter(function (x) { return x.id !== id; }); hideModal(); render(); showToast('Device removed', 'warning'); }
export function openAddRoom() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Room</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Room name</label><input class="input" id="room-name" placeholder="e.g. Home Office"></div><div><label>Icon</label><select class="input" id="room-icon">' + iconOpts(roomIcons, 'fa-couch') + '</select></div><button class="btn btn-primary w-full" onclick="saveRoom()">Add Room</button></div></div>'); }
export function saveRoom() { var name = val('room-name').trim(); if (!name) { showToast('Enter a room name', 'error'); return; } var id = 'room' + (++S.nid); S.rooms.push({ id: id, name: name, icon: val('room-icon') || 'fa-house-chimney' }); hideModal(); render(); showToast(name + ' added', 'success'); }

/* ===== Scenes ===== */
export function activateScene(id) { var sc = S.scenes.find(function (s) { return s.id === id; }); if (!sc) return; var a = sc.actions; if (a.lightsAllOff) S.lights.forEach(function (l) { l.on = false; }); if (a.lightsOn) a.lightsOn.forEach(function (rm) { S.lights.filter(function (l) { return l.room === rm; }).forEach(function (l) { l.on = true; l.brightness = 80; }); }); if (a.lightsDim) S.lights.filter(function (l) { return l.on; }).forEach(function (l) { l.brightness = Math.min(l.brightness, a.lightsDim); }); if (a.devicesOn) a.devicesOn.forEach(function (did) { var d = S.devices.find(function (x) { return x.id === did; }); if (d) d.status = 'on'; }); if (a.lockAll) S.devices.filter(function (d) { return d.type === 'lock'; }).forEach(function (d) { d.status = 'locked'; d.icon = 'fa-lock'; }); if (a.arm) S.securityArmed = true; if (a.thermostat) { S.thermostat.target = a.thermostat; S.thermostat.on = true; } S.alerts.unshift({ id: ++S.nid, type: 'system', msg: 'Scene "' + sc.name + '" activated', time: 'Just now', sev: 'success', seen: false }); var ov = document.getElementById('scene-overlay'); document.getElementById('scene-splash-inner').innerHTML = '<div class="w-20 h-20 rounded-2xl flex items-center justify-center mx-auto mb-4" style="background:' + esc(sc.color) + '20;color:' + esc(sc.color) + ';font-size:32px"><i class="fa-solid ' + esc(sc.icon) + '"></i></div><h2 class="text-2xl font-bold mb-2">' + esc(sc.name) + '</h2><p class="text-[var(--muted)] text-sm">' + esc(sc.desc) + '</p>'; ov.classList.add('show'); setTimeout(function () { ov.classList.remove('show'); render(); }, 1500); showToast('Scene "' + sc.name + '" activated', 'success'); }

/* ===== Tasks: chores & shopping ===== */
export function toggleChore(id) { var c = S.chores.find(function (x) { return x.id === id; }); if (!c) return; c.done = !c.done; if (c.done) { S.chorePoints[c.assignee] = (S.chorePoints[c.assignee] || 0) + c.pts; S.alerts.unshift({ id: ++S.nid, type: 'chore', msg: (gm(c.assignee) || {}).name + ' completed "' + c.name + '" (+' + c.pts + ' pts)', time: 'Just now', sev: 'success', seen: false }); showToast('+' + c.pts + ' points!', 'success'); } else { S.chorePoints[c.assignee] = Math.max(0, (S.chorePoints[c.assignee] || 0) - c.pts); } render(); }
export function toggleShop(id) { var s = S.shopping.find(function (x) { return x.id === id; }); if (s) s.checked = !s.checked; render(); }
export function deleteShop(id) { S.shopping = S.shopping.filter(function (s) { return s.id !== id; }); render(); showToast('Item removed', 'warning'); }
export function clearChecked() { S.shopping = S.shopping.filter(function (s) { return !s.checked; }); render(); showToast('Cleared', 'info'); }
export function openAddChore() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Chore</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="ch-name" placeholder="e.g. Clean windows"></div><div class="grid grid-cols-2 gap-3"><div><label>Assign To</label><select class="input" id="ch-who">' + S.members.map(function (m) { return '<option value="' + m.id + '">' + esc(m.name) + '</option>'; }).join('') + '</select></div><div><label>Day</label><select class="input" id="ch-day">' + dayNames.map(function (d, i) { return '<option value="' + i + '">' + d + '</option>'; }).join('') + '</select></div></div><div><label>Points</label><input class="input" id="ch-pts" type="number" value="10"></div><button class="btn btn-primary w-full" onclick="saveChore()">Add</button></div></div>'); }
export function saveChore() { var name = document.getElementById('ch-name').value.trim(), who = +document.getElementById('ch-who').value, day = +document.getElementById('ch-day').value, pts = +document.getElementById('ch-pts').value || 10; if (!name) { showToast('Enter chore name', 'error'); return; } S.chores.push({ id: ++S.nid, name: name, assignee: who, day: day, done: false, pts: pts, icon: 'fa-circle-check' }); hideModal(); render(); showToast('Chore added', 'success'); }
export function openAddShop() { showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Item</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Item</label><input class="input" id="sh-name" placeholder="e.g. Milk"></div><div class="grid grid-cols-2 gap-3"><div><label>Quantity</label><input class="input" id="sh-qty" placeholder="2 gallons"></div><div><label>Category</label><select class="input" id="sh-cat"><option>Produce</option><option>Dairy</option><option>Meat</option><option>Bakery</option><option>Grains</option><option>Pantry</option><option>Household</option><option>Other</option></select></div></div><button class="btn btn-primary w-full" onclick="saveShop()">Add</button></div></div>'); }
export function saveShop() { var name = document.getElementById('sh-name').value.trim(), qty = document.getElementById('sh-qty').value.trim() || '1', cat = document.getElementById('sh-cat').value; if (!name) { showToast('Enter item name', 'error'); return; } S.shopping.push({ id: ++S.nid, name: name, qty: qty, checked: false, addedBy: S.userId, cat: cat }); hideModal(); render(); showToast('Item added', 'success'); }

/* ===== Family ===== */
var _memColor = '#10B981';
export function openAddMember() { if (!ia()) { showToast('Admin only', 'error'); return; } var colors = ['#10B981', '#F59E0B', '#EF4444', '#3B82F6', '#8B5CF6', '#EC4899', '#06B6D4', '#F97316']; showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Member</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Name</label><input class="input" id="mem-name" placeholder="Full name"></div><div><label>Role</label><select class="input" id="mem-role"><option value="member">Member</option><option value="admin">Admin</option></select></div><div><label>Color</label><div class="flex gap-2 mt-1" id="mem-colors">' + colors.map(function (c, i) { return '<div class="w-8 h-8 rounded-lg cursor-pointer border-2 transition hover:scale-110 ' + (i === 0 ? 'border-white' : 'border-transparent') + '" style="background:' + c + '" onclick="selectMemColor(this,\'' + c + '\')"></div>'; }).join('') + '</div></div><button class="btn btn-primary w-full" onclick="saveMember()">Add</button></div></div>'); _memColor = colors[0]; }
export function selectMemColor(el, color) { _memColor = color; el.parentElement.querySelectorAll('div').forEach(function (d) { d.style.borderColor = 'transparent'; }); el.style.borderColor = 'white'; }
export function saveMember() { var name = document.getElementById('mem-name').value.trim(), role = document.getElementById('mem-role').value; if (!name) { showToast('Enter a name', 'error'); return; } var init = name.split(' ').map(function (w) { return w[0]; }).join('').toUpperCase().slice(0, 2); S.members.push({ id: ++S.nid, name: name, role: role, status: 'home', color: _memColor || '#10B981', init: init }); hideModal(); renderNav(); render(); showToast(name + ' added', 'success'); }
export function openEditMember(id) {
  var m = gm(id); if (!m) return;
  var admin = ia(); var self = m.id === S.userId;
  if (!admin && !self) { showToast('Admin only', 'error'); return; }
  _memColor = m.color || '#10B981';
  var statuses = ['home', 'school', 'out', 'work', 'gym'];
  var colors = ['#10B981', '#F59E0B', '#EF4444', '#3B82F6', '#8B5CF6', '#EC4899', '#06B6D4', '#F97316'];
  var roleField = admin ? '<div><label>Role</label><select class="input" id="edit-role"><option value="member" ' + (m.role === 'member' ? 'selected' : '') + '>Member</option><option value="admin" ' + (m.role === 'admin' ? 'selected' : '') + '>Admin</option></select></div>' : '';
  var removeBtn = (admin && !self) ? '<button class="btn btn-danger flex-1" onclick="removeMember(' + m.id + ')"><i class="fa-solid fa-user-minus"></i>Remove</button>' : '';
  showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Edit ' + esc(m.name) + '</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3">'
    + '<div><label>Name</label><input class="input" id="edit-name" value="' + esc(m.name) + '" placeholder="Full name"></div>'
    + '<div><label>Status</label><select class="input" id="edit-status">' + statuses.map(function (s) { return '<option value="' + s + '" ' + (m.status === s ? 'selected' : '') + '>' + s + '</option>'; }).join('') + '</select></div>'
    + roleField
    + '<div><label>Color</label><div class="flex gap-2 mt-1" id="mem-colors">' + colors.map(function (c) { return '<div class="w-8 h-8 rounded-lg cursor-pointer border-2 transition hover:scale-110 ' + (c === m.color ? 'border-white' : 'border-transparent') + '" style="background:' + c + '" onclick="selectMemColor(this,\'' + c + '\')"></div>'; }).join('') + '</div></div>'
    + '<div class="flex gap-3 pt-1"><button class="btn btn-primary flex-1" onclick="updateMember(' + m.id + ')"><i class="fa-solid fa-check"></i>Save</button>' + removeBtn + '</div></div></div>');
}
export function updateMember(id) {
  var m = gm(id); if (!m) return;
  var name = (document.getElementById('edit-name') || {}).value; name = (name || '').trim();
  if (!name) { showToast('Enter a name', 'error'); return; }
  m.name = name; m.init = name.split(' ').map(function (w) { return w[0]; }).join('').toUpperCase().slice(0, 2);
  m.status = document.getElementById('edit-status').value;
  var roleEl = document.getElementById('edit-role'); if (roleEl) m.role = roleEl.value;
  m.color = _memColor || m.color;
  hideModal(); renderNav(); runAutomations({ type: 'presence' }); render(); showToast(m.name + ' updated', 'success');
}
export function removeMember(id) { if (!ia()) { showToast('Admin only', 'error'); return; } if (id === S.userId) { showToast("You can't remove yourself", 'error'); return; } if (S.members.length <= 1) { showToast('A household needs at least one member', 'error'); return; } S.members = S.members.filter(function (m) { return m.id !== id; }); hideModal(); renderNav(); render(); showToast('Member removed', 'warning'); }

/* Household / family-level settings */
export function openEditFamilyName() {
  if (!ia()) { showToast('Admin only', 'error'); return; }
  showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Family Name</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>What should we call your household?</label><input class="input" id="fam-name" value="' + esc(S.householdName || '') + '" placeholder="e.g. The Cantila Home" maxlength="80"></div><button class="btn btn-primary w-full" onclick="saveFamilyName()"><i class="fa-solid fa-check"></i>Save</button></div></div>');
}
export function saveFamilyName() {
  var name = (val('fam-name') || '').trim(); if (!name) { showToast('Enter a family name', 'error'); return; }
  S.householdName = name; hideModal(); renderNav(); render(); showToast('Family name updated', 'success');
}

/* ===== Schedule: events ===== */
export function openAddEvent() { var cats = Object.keys(catColors); showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">Add Event</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div><label>Title</label><input class="input" id="evt-title" placeholder="Event title"></div><div class="grid grid-cols-2 gap-3"><div><label>Date</label><input class="input" id="evt-date" type="date" value="' + S.selectedDate + '"></div><div><label>Time</label><input class="input" id="evt-time" type="time"></div></div><div class="grid grid-cols-2 gap-3"><div><label>Category</label><select class="input" id="evt-cat">' + cats.map(function (c) { return '<option value="' + c + '">' + c + '</option>'; }).join('') + '</select></div><div><label>Assign To</label><select class="input" id="evt-member">' + S.members.map(function (m) { return '<option value="' + m.id + '">' + esc(m.name) + '</option>'; }).join('') + '</select></div></div><div><label>Description</label><input class="input" id="evt-desc" placeholder="Optional"></div><button class="btn btn-primary w-full" onclick="saveEvent()">Save</button></div></div>'); }
export function saveEvent() { var title = document.getElementById('evt-title').value.trim(), date = document.getElementById('evt-date').value, time = document.getElementById('evt-time').value, cat = document.getElementById('evt-cat').value, memberId = +document.getElementById('evt-member').value, desc = document.getElementById('evt-desc').value.trim(); if (!title || !date || !time) { showToast('Fill required fields', 'error'); return; } S.events.push({ id: ++S.nid, title: title, date: date, time: time, memberId: memberId, cat: cat, desc: desc }); hideModal(); render(); showToast('Event added', 'success'); }
export function viewEvent(id) { var e = S.events.find(function (x) { return x.id === id; }); if (!e) return; var m = gm(e.memberId); showModal('<div class="p-5"><div class="flex items-center justify-between mb-4"><h3 class="font-bold">' + esc(e.title) + '</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-3"><div class="flex items-center gap-3"><i class="fa-regular fa-calendar text-[var(--muted)]"></i><span>' + fd(e.date) + '</span></div><div class="flex items-center gap-3"><i class="fa-regular fa-clock text-[var(--muted)]"></i><span>' + esc(e.time) + '</span></div><div class="flex items-center gap-3"><i class="fa-solid fa-tag text-[var(--muted)]"></i><span class="capitalize">' + esc(e.cat) + '</span></div><div class="flex items-center gap-3">' + (m ? avatarLite(m) : '') + '<span>' + esc(m ? m.name : 'Unknown') + '</span></div>' + (e.desc ? '<p class="text-sm text-[var(--muted)] pt-2 border-t border-[var(--border)]">' + esc(e.desc) + '</p>' : '') + '</div><div class="flex gap-3 mt-4"><button class="btn btn-danger btn-sm flex-1" onclick="deleteEvent(' + e.id + ')"><i class="fa-solid fa-trash-can"></i>Delete</button><button class="btn btn-secondary btn-sm flex-1" onclick="hideModal()">Close</button></div></div>'); }
function avatarLite(m) { return '<div class="avatar" style="background:' + esc(m.color) + ';width:24px;height:24px;font-size:9px;border-radius:6px">' + esc(m.init) + '</div>'; }
export function deleteEvent(id) { S.events = S.events.filter(function (e) { return e.id !== id; }); hideModal(); render(); showToast('Event deleted', 'warning'); }

/* ===== Notifications ===== */
export function toggleNotif() { S.notifOpen = !S.notifOpen; renderNotifPanel(); }
export function renderNotifPanel() {
  var p = document.getElementById('notif-panel'); var dot = document.getElementById('notif-dot'); var unseen = S.alerts.filter(function (a) { return !a.seen; }).length; if (dot) dot.style.display = unseen > 0 ? 'block' : 'none';
  if (!p) return;
  if (!S.notifOpen) { p.classList.remove('show'); return; }
  p.classList.add('show');
  var colors = { info: 'var(--blue)', warning: 'var(--amber)', success: 'var(--accent)', danger: 'var(--red)' }; var bgs = { info: 'rgba(59,130,246,.12)', warning: 'rgba(245,158,11,.12)', success: 'rgba(16,185,129,.12)', danger: 'rgba(239,68,68,.12)' }; var icons = { motion: 'fa-person-walking', door: 'fa-door-open', system: 'fa-shield-halved', light: 'fa-lightbulb', climate: 'fa-temperature-half', device: 'fa-plug', chore: 'fa-check-circle', budget: 'fa-wallet', automation: 'fa-wand-magic-sparkles', voice: 'fa-microphone' };
  var h = '<div class="p-4 border-b border-[var(--border)] flex items-center justify-between"><h4 class="font-semibold text-sm">Notifications</h4><button class="text-xs text-[var(--accent)] hover:underline" onclick="clearNotifs()">Mark all read</button></div><div class="overflow-y-auto" style="max-height:340px">';
  for (var i = 0; i < Math.min(12, S.alerts.length); i++) { var a = S.alerts[i]; h += '<div class="flex gap-3 p-3 hover:bg-[var(--surface)] transition cursor-pointer border-b border-[var(--border)]"><div class="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0" style="background:' + bgs[a.sev] + ';color:' + colors[a.sev] + ';font-size:13px"><i class="fa-solid ' + (icons[a.type] || 'fa-bell') + '"></i></div><div class="min-w-0"><div class="text-xs font-medium">' + esc(a.msg) + '</div><div class="text-[10px] text-[var(--muted)]">' + esc(a.time) + '</div></div></div>'; }
  h += '</div>'; p.innerHTML = h; S.alerts.forEach(function (a) { a.seen = true; });
}
export function clearNotifs() { S.alerts.forEach(function (a) { a.seen = true; }); renderNotifPanel(); showToast('All marked as read', 'info'); }

/* ===== Global search ===== */
export function openSearch() { document.getElementById('search-overlay').classList.add('show'); setTimeout(function () { document.getElementById('search-input').focus(); }, 100); }
export function closeSearch() { document.getElementById('search-overlay').classList.remove('show'); document.getElementById('search-input').value = ''; document.getElementById('search-results').innerHTML = ''; }
// Collect search matches across every household domain.
function collectResults(q) {
  q = q.toLowerCase(); var items = [];
  S.events.forEach(function (e) { if ((e.title || '').toLowerCase().indexOf(q) >= 0 || (e.desc || '').toLowerCase().indexOf(q) >= 0) items.push({ icon: 'fa-calendar', label: e.title, sub: e.date + ' ' + e.time, color: catColors[e.cat] || '#6B7B8D', act: 'viewEvent(' + e.id + ')' }); });
  S.transactions.forEach(function (t) { if ((t.cat || '').toLowerCase().indexOf(q) >= 0 || (t.note || '').toLowerCase().indexOf(q) >= 0) items.push({ icon: t.type === 'income' ? 'fa-arrow-down' : 'fa-arrow-up', label: t.cat + ': $' + t.amount, sub: t.note, color: t.type === 'income' ? 'var(--accent)' : 'var(--red)', act: "navigate('finance')" }); });
  S.devices.forEach(function (d) { if (d.name.toLowerCase().indexOf(q) >= 0) items.push({ icon: d.icon, label: d.name, sub: d.type, color: '#6B7B8D', act: "navigate('home')" }); });
  S.lights.forEach(function (l) { if (l.name.toLowerCase().indexOf(q) >= 0) items.push({ icon: 'fa-lightbulb', label: l.name, sub: (S.rooms.find(function (r2) { return r2.id === l.room; }) || {}).name || '', color: 'var(--amber)', act: "navigate('home')" }); });
  (S.automations || []).forEach(function (a) { if ((a.name || '').toLowerCase().indexOf(q) >= 0) items.push({ icon: a.icon || 'fa-wand-magic-sparkles', label: a.name, sub: 'Automation', color: 'var(--purple)', act: "navigate('home')" }); });
  S.members.forEach(function (m) { if (m.name.toLowerCase().indexOf(q) >= 0) items.push({ icon: 'fa-user', label: m.name, sub: m.role, color: m.color, act: "navigate('family')" }); });
  return items;
}
function resultsHtml(items, closer) {
  var h = ''; for (var i = 0; i < Math.min(10, items.length); i++) { var it = items[i]; h += '<div class="search-res flex items-center gap-3 p-3 rounded-lg cursor-pointer hover:bg-[var(--surface)] transition" onclick="' + it.act + ';' + closer + '"><div class="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0" style="background:' + esc(it.color) + '20;color:' + esc(it.color) + ';font-size:13px"><i class="fa-solid ' + esc(it.icon) + '"></i></div><div class="min-w-0"><div class="text-sm font-medium truncate">' + esc(it.label) + '</div><div class="text-[11px] text-[var(--muted)]">' + esc(it.sub) + '</div></div></div>'; }
  return h;
}
export function doSearch(q) {
  var r = document.getElementById('search-results'); if (!r) return; if (!q.trim()) { r.innerHTML = '<div class="p-6 text-center text-sm text-[var(--muted)]">Type to search...</div>'; return; }
  var items = collectResults(q);
  if (!items.length) { r.innerHTML = '<div class="p-6 text-center text-sm text-[var(--muted)]">No results found</div>'; return; }
  r.innerHTML = resultsHtml(items, 'closeSearch()');
}

/* ===== Header search bar (top of every screen) ===== */
export function navSearch(q) {
  var box = document.getElementById('navsearch-results'); if (!box) return;
  if (!q.trim()) { box.classList.remove('show'); box.innerHTML = ''; return; }
  var items = collectResults(q);
  box.innerHTML = items.length ? resultsHtml(items, 'closeNavSearch()') : '<div class="p-3 text-center text-xs text-[var(--muted)]">No results</div>';
  box.classList.add('show');
}
export function closeNavSearch() { var box = document.getElementById('navsearch-results'); if (box) box.classList.remove('show'); }
// The header search shows as a magnifying-glass icon and expands leftward on demand.
export function toggleNavSearch() {
  var w = document.getElementById('navsearch-wrap'); if (!w) return;
  var inp = document.getElementById('navsearch');
  if (w.classList.contains('open')) { w.classList.remove('open'); if (inp) inp.value = ''; closeNavSearch(); }
  else { w.classList.add('open'); setTimeout(function () { if (inp) inp.focus(); }, 60); }
}
export function collapseNavSearch() {
  var w = document.getElementById('navsearch-wrap'); var inp = document.getElementById('navsearch');
  if (inp && inp.value.trim()) return; // keep open while a query is being viewed
  if (w) w.classList.remove('open'); closeNavSearch();
}
export function navSearchKey(e) {
  var box = document.getElementById('navsearch-results'); if (!box) return;
  var rows = box.querySelectorAll('.search-res');
  if (e.key === 'Escape') { closeNavSearch(); if (e.target && e.target.blur) e.target.blur(); return; }
  if (e.key === 'Enter') { var sel = box.querySelector('.search-res.sel') || rows[0]; if (sel) { sel.click(); e.target.value = ''; } return; }
  if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
    e.preventDefault(); if (!rows.length) return;
    var cur = box.querySelector('.search-res.sel'); var idx = -1; for (var i = 0; i < rows.length; i++) { if (rows[i] === cur) { idx = i; break; } }
    if (cur) cur.classList.remove('sel');
    idx = e.key === 'ArrowDown' ? (idx + 1) % rows.length : (idx - 1 + rows.length) % rows.length;
    rows[idx].classList.add('sel'); rows[idx].scrollIntoView({ block: 'nearest' });
  }
}
