// Pure render helpers — given a data row, return an HTML string. Every
// user-controlled field is escaped via esc() to prevent stored XSS.
import { S, esc, avatar, money, fd, gm, ia, budgetSpent, CY, CM, CD } from './core.js';
import { catColors, statusIcons, devTypeColors, dayNames, debtMeta } from './constants.js';

export function statCard(cls, icon, iconColor, label, value, sub) { return '<div class="card stat-card ' + cls + '" style="padding:16px"><div class="flex items-center gap-2 mb-2"><i class="fa-solid ' + icon + ' text-sm" style="color:' + iconColor + '" aria-hidden="true"></i><span class="text-xs text-[var(--muted)]">' + label + '</span></div><div class="text-2xl font-bold">' + value + '</div>' + (sub ? '<div class="text-xs text-[var(--muted)]">' + sub + '</div>' : '') + '</div>'; }

export function evtRow(e) { var m = gm(e.memberId); return '<div class="flex items-center gap-3 p-2.5 rounded-xl hover:bg-[var(--surface2)] transition cursor-pointer" onclick="viewEvent(' + e.id + ')"><div class="w-1 h-9 rounded-full" style="background:' + (catColors[e.cat] || '#6B7B8D') + '"></div><div class="flex-1 min-w-0"><div class="font-medium text-sm">' + esc(e.title) + '</div><div class="text-[11px] text-[var(--muted)]">' + fd(e.date) + ' at ' + esc(e.time) + '</div></div>' + avatar(m, 26, 26, 9, 7) + '</div>'; }

export function txRow(t) { var m = gm(t.memberId); var ic = t.type === 'income' ? 'fa-arrow-down' : 'fa-arrow-up'; var col = t.type === 'income' ? 'var(--accent)' : 'var(--red)'; var bg = t.type === 'income' ? 'rgba(16,185,129,.12)' : 'rgba(239,68,68,.12)'; var sign = t.type === 'income' ? '+' : '-'; var del = (ia() || t.memberId === S.userId) ? '<button class="text-[var(--muted)] hover:text-[var(--red)] transition text-xs" onclick="deleteTx(' + t.id + ')" aria-label="Delete transaction"><i class="fa-solid fa-trash-can"></i></button>' : ''; return '<div class="tx-row"><div class="w-9 h-9 rounded-xl flex items-center justify-center" style="background:' + bg + '"><i class="fa-solid ' + ic + ' text-xs" style="color:' + col + '"></i></div><div class="flex-1 min-w-0"><div class="font-medium text-sm">' + esc(t.cat) + '</div><div class="text-[11px] text-[var(--muted)]">' + esc(t.note || t.cat) + ' &middot; ' + fd(t.date) + '</div></div><div class="text-sm font-bold" style="color:' + col + '">' + sign + money(t.amount) + '</div>' + avatar(m, 26, 26, 9, 7) + del + '</div>'; }

export function memberCard(m) { var mE = S.events.filter(function (e) { return e.memberId === m.id; }).length; var mI = S.transactions.filter(function (t) { return t.memberId === m.id && t.type === 'income'; }).reduce(function (s, t) { return s + t.amount; }, 0); var mX = S.transactions.filter(function (t) { return t.memberId === m.id && t.type === 'expense'; }).reduce(function (s, t) { return s + t.amount; }, 0); var pts = S.chorePoints[m.id] || 0; var canEdit = ia() || m.id === S.userId; var editLabel = m.id === S.userId ? 'Edit my profile' : 'Manage'; var editBtn = canEdit ? '<button class="btn btn-sm btn-secondary w-full mt-3" onclick="openEditMember(' + m.id + ')"><i class="fa-solid fa-pen"></i> ' + editLabel + '</button>' : ''; return '<div class="card text-center"><div class="flex justify-center mb-2">' + avatar(m, 52, 52, 17, 14) + '</div><h4 class="font-semibold text-lg">' + esc(m.name) + '</h4><div class="flex items-center justify-center gap-2 mt-1 mb-3"><span class="badge ' + (m.role === 'admin' ? 'badge-admin' : 'badge-member') + '">' + esc(m.role) + '</span><span class="text-xs text-[var(--muted)] capitalize"><i class="fa-solid ' + (statusIcons[m.status] || 'fa-circle') + ' text-[10px]"></i> ' + esc(m.status) + '</span></div><div class="grid grid-cols-3 gap-2 mt-3 pt-3 border-t border-[var(--border)]"><div><div class="text-base font-bold">' + mE + '</div><div class="text-[9px] text-[var(--muted)]">Events</div></div><div><div class="text-base font-bold text-[var(--accent)]">$' + mI.toLocaleString() + '</div><div class="text-[9px] text-[var(--muted)]">Income</div></div><div><div class="text-base font-bold text-[var(--red)]">$' + mX.toLocaleString() + '</div><div class="text-[9px] text-[var(--muted)]">Expenses</div></div></div><div class="text-xs text-[var(--muted)] mt-2">' + pts + ' chore points</div>' + editBtn + '</div>'; }

export function lightCard(l) { var room = S.rooms.find(function (r) { return r.id === l.room; }); var rn = room ? room.name : ''; var slider = l.on ? '<div class="flex items-center gap-2 mt-2"><i class="fa-solid fa-sun text-[10px] text-[var(--muted)]"></i><input type="range" class="brightness-slider flex-1" min="5" max="100" value="' + l.brightness + '" onchange="setBrightness(' + l.id + ',+this.value)" aria-label="' + esc(l.name) + ' brightness"><span class="text-[10px] text-[var(--muted)] w-7 text-right">' + l.brightness + '%</span></div>' : ''; return '<div class="p-3 rounded-xl border border-[var(--border)] ' + (l.on ? 'light-on' : '') + '" style="background:' + (l.on ? 'rgba(245,158,11,.03)' : 'var(--bg2)') + '"><div class="flex items-center justify-between mb-2"><div class="flex items-center gap-2"><div class="dev-icon" title="Manage" style="cursor:pointer;background:' + (l.on ? 'rgba(245,158,11,.12)' : 'rgba(123,140,168,.08)') + ';width:34px;height:34px;border-radius:9px;font-size:13px" onclick="openManageDevice(\'light\',' + l.id + ')" aria-label="Manage ' + esc(l.name) + '"><i class="fa-solid fa-lightbulb" style="color:' + (l.on ? 'var(--amber)' : 'var(--muted)') + '"></i></div><div><div class="font-medium text-xs">' + esc(l.name) + '</div><div class="text-[10px] text-[var(--muted)]">' + esc(rn) + '</div></div></div><div class="toggle ' + (l.on ? 'on amber' : '') + '" style="width:40px;height:22px" onclick="toggleLight(' + l.id + ')" aria-label="Toggle ' + esc(l.name) + '" aria-pressed="' + (l.on ? 'true' : 'false') + '"></div></div>' + slider + '</div>'; }

export function lockRow(d) { var room = S.rooms.find(function (r) { return r.id === d.room; }); var rn = room ? room.name : ''; return '<div class="flex items-center justify-between p-2.5 rounded-xl bg-[var(--bg2)]"><div class="flex items-center gap-2"><div class="dev-icon" style="background:' + (d.status === 'locked' ? 'rgba(16,185,129,.12)' : 'rgba(245,158,11,.12)') + ';width:34px;height:34px;border-radius:9px;font-size:13px"><i class="fa-solid ' + (d.status === 'locked' ? 'fa-lock' : 'fa-lock-open') + '" style="color:' + (d.status === 'locked' ? 'var(--accent)' : 'var(--amber)') + '"></i></div><div><div class="font-medium text-xs">' + esc(d.name) + '</div><div class="text-[10px] text-[var(--muted)]">' + esc(rn) + '</div></div></div><div class="flex items-center gap-1.5"><span class="badge ' + (d.status === 'locked' ? 'badge-locked' : 'badge-unlocked') + ' text-[10px]">' + esc(d.status) + '</span><div class="toggle ' + (d.status === 'locked' ? 'on' : '') + '" style="width:40px;height:22px" onclick="toggleLock(' + d.id + ')" aria-label="Toggle ' + esc(d.name) + '"></div></div></div>'; }

export function deviceCard(d) { var room = S.rooms.find(function (r) { return r.id === d.room; }); var rn = room ? room.name : ''; var isOn = d.status !== 'off' && d.status !== 'inactive'; var tc = devTypeColors[d.type] || '#6B7280'; return '<div class="p-3 rounded-xl border border-[var(--border)]" style="background:' + (isOn ? tc + '06' : 'var(--bg2)') + '"><div class="flex items-center justify-between mb-1"><div class="flex items-center gap-2"><div class="dev-icon" title="Manage" style="cursor:pointer;background:' + (isOn ? tc + '18' : 'rgba(123,140,168,.08)') + ';color:' + (isOn ? tc : 'var(--muted)') + ';width:34px;height:34px;border-radius:9px;font-size:13px" onclick="openManageDevice(\'device\',' + d.id + ')" aria-label="Manage ' + esc(d.name) + '"><i class="fa-solid ' + esc(d.icon) + '"></i></div><div><div class="font-medium text-xs">' + esc(d.name) + '</div><div class="text-[10px] text-[var(--muted)]">' + esc(rn) + (d.ip ? ' &middot; ' + esc(d.ip) : '') + '</div></div></div><div class="toggle ' + (isOn ? 'on' : '') + '" style="width:40px;height:22px" onclick="toggleDevice(' + d.id + ')" aria-label="Toggle ' + esc(d.name) + '"></div></div><span class="badge ' + (isOn ? 'badge-on' : 'badge-off') + ' text-[10px]">' + esc(d.status) + '</span>' + (d.source === 'discovered' ? '<span class="badge badge-active text-[10px] ml-1"><i class="fa-solid fa-wifi text-[8px]"></i> linked</span>' : '') + '</div>'; }

export function sensorRow(s) { var room = S.rooms.find(function (r) { return r.id === s.room; }); return '<div class="flex items-center justify-between p-2 rounded-lg bg-[var(--bg2)]"><div class="flex items-center gap-2"><div class="w-7 h-7 rounded-lg flex items-center justify-center" style="background:' + (s.status === 'active' ? 'rgba(6,182,212,.12)' : 'rgba(239,68,68,.12)') + '"><i class="fa-solid ' + esc(s.icon) + ' text-[11px]" style="color:' + (s.status === 'active' ? 'var(--cyan)' : 'var(--red)') + '"></i></div><div><div class="text-xs font-medium">' + esc(s.name) + '</div><div class="text-[9px] text-[var(--muted)]">' + esc(room ? room.name : '') + '</div></div></div><div class="toggle ' + (s.status === 'active' ? 'on' : '') + '" style="width:38px;height:20px" onclick="toggleSensor(' + s.id + ')" aria-label="Toggle ' + esc(s.name) + '"></div></div>'; }

export function camCard(c) {
  if (c.status !== 'active') { return '<div class="cam-feed"><div class="absolute inset-0 flex flex-col items-center justify-center text-[var(--muted)] text-xs gap-1"><i class="fa-solid fa-video-slash text-lg"></i><span>' + esc(c.name) + ' — Off</span></div><div class="cam-label"><span>' + esc(c.name) + '</span></div></div>'; }
  var tag = c.brand ? esc(c.brand).toUpperCase() : 'SIMULATED';
  var sub = esc(c.name) + (c.camType ? ' · ' + esc(c.camType) : '');
  var label = '<div class="cam-rec">REC</div><div style="position:absolute;top:6px;right:8px;font-size:8px;font-family:monospace;color:rgba(255,255,255,.55);letter-spacing:1px">' + tag + '</div><div class="cam-label"><span>' + sub + '</span><span class="cam-time"></span></div>';
  // A real stream (MJPEG/snapshot/any image-renderable URL) is shown directly;
  // on error we fall back to the simulated canvas, so any brand works.
  var media;
  if (c.stream) { media = '<img src="' + esc(c.stream) + '" alt="' + esc(c.name) + ' feed" style="width:100%;height:100%;object-fit:cover;display:block" onerror="this.style.display=\'none\';var cv=document.getElementById(\'cam-' + c.id + '\');if(cv)cv.style.display=\'block\'"><canvas id="cam-' + c.id + '" width="320" height="200" style="display:none;position:absolute;inset:0;width:100%;height:100%"></canvas>'; }
  else { media = '<canvas id="cam-' + c.id + '" width="320" height="200"></canvas>'; }
  return '<div class="cam-feed">' + media + label + '</div>';
}

export function choreRow(c) { var m = gm(c.assignee); return '<div class="chore-row ' + (c.done ? 'done' : '') + '"><div class="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0" style="background:' + (c.done ? 'rgba(16,185,129,.12)' : 'rgba(123,140,168,.08)') + ';color:' + (c.done ? 'var(--accent)' : 'var(--muted)') + ';font-size:13px"><i class="fa-solid ' + (c.done ? 'fa-check' : esc(c.icon)) + '"></i></div><div class="flex-1 min-w-0"><div class="chore-name font-medium text-sm">' + esc(c.name) + '</div><div class="text-[10px] text-[var(--muted)]">' + dayNames[c.day] + ' &middot; ' + c.pts + ' pts</div></div>' + avatar(m, 26, 26, 9, 7) + '<div class="toggle ' + (c.done ? 'on' : '') + '" style="width:40px;height:22px" onclick="toggleChore(' + c.id + ')" aria-label="Toggle ' + esc(c.name) + '"></div></div>'; }

export function shopRow(s) { var chk = s.checked ? '<i class="fa-solid fa-check text-[10px] text-white"></i>' : ''; var nm = s.checked ? 'line-through text-[var(--muted)]' : ''; return '<div class="shop-item"><div class="shop-check ' + (s.checked ? 'on' : '') + '" onclick="toggleShop(' + s.id + ')" aria-label="Toggle ' + esc(s.name) + '">' + chk + '</div><div class="flex-1 min-w-0"><span class="text-sm ' + nm + '">' + esc(s.name) + '</span><span class="text-[10px] text-[var(--muted)] ml-2">' + esc(s.qty) + '</span></div><span class="text-[10px] px-1.5 py-0.5 rounded bg-[var(--surface2)] text-[var(--muted)]">' + esc(s.cat) + '</span><button class="text-[var(--muted)] hover:text-[var(--red)] text-xs ml-1" onclick="deleteShop(' + s.id + ')" aria-label="Remove ' + esc(s.name) + '"><i class="fa-solid fa-xmark"></i></button></div>'; }

export function budgetCard(b) { var spent = budgetSpent(b.cat); var pct = Math.min(100, Math.round(spent / b.limit * 100)); var col = pct >= 100 ? 'var(--red)' : pct > 80 ? 'var(--amber)' : 'var(--accent)'; return '<div class="p-3 rounded-xl bg-[var(--bg2)]"><div class="flex justify-between text-xs mb-1.5"><span class="font-medium">' + esc(b.cat) + '</span><span style="color:' + col + '">' + pct + '%</span></div><div class="prog-bar"><div class="prog-fill" style="width:' + pct + '%;background:' + col + '"></div></div><div class="text-[10px] text-[var(--muted)] mt-1">' + money(spent) + ' / ' + money(b.limit) + (spent > b.limit ? ' &middot; <span style="color:var(--red)">over</span>' : '') + '</div></div>'; }

export function savingsCard(s) { var pct = Math.round(s.current / s.target * 100); var circ = 2 * Math.PI * 38; var offset = circ - (pct / 100) * circ; return '<div class="text-center p-4 rounded-xl border border-[var(--border)]" style="background:var(--bg2);position:relative"><svg width="90" height="90" class="mx-auto mb-2" aria-hidden="true"><circle cx="45" cy="45" r="38" fill="none" stroke="var(--border)" stroke-width="5"/><circle class="progress-ring" cx="45" cy="45" r="38" fill="none" stroke="' + esc(s.color) + '" stroke-width="5" stroke-linecap="round" stroke-dasharray="' + circ + '" stroke-dashoffset="' + offset + '"/></svg><div style="position:absolute;top:38px;left:50%;transform:translateX(-50%)"><i class="fa-solid ' + esc(s.icon) + '" style="color:' + esc(s.color) + ';font-size:14px"></i></div><div class="font-semibold text-sm mt-1">' + esc(s.name) + '</div><div class="text-lg font-bold" style="color:' + esc(s.color) + '">$' + s.current.toLocaleString() + '</div><div class="text-[11px] text-[var(--muted)]">of $' + s.target.toLocaleString() + ' (' + pct + '%)</div><button class="btn btn-sm btn-secondary w-full mt-2" onclick="addToSavings(' + s.id + ')"><i class="fa-solid fa-plus"></i>Add</button></div>'; }

export function recurringCard(r) { var isBill = r.kind !== 'income'; var col = isBill ? 'var(--red)' : 'var(--accent)'; var icon = isBill ? 'fa-file-invoice-dollar' : 'fa-arrow-down'; var dd = new Date(r.next + 'T00:00:00'); var days = Math.round((dd - new Date(CY, CM, CD)) / 86400000); var due = isNaN(days) ? '' : days < 0 ? 'Overdue' : days === 0 ? 'Due today' : days === 1 ? 'Tomorrow' : 'in ' + days + ' days'; var dueCol = days <= 0 ? 'var(--red)' : days <= 3 ? 'var(--amber)' : 'var(--muted)'; return '<div class="flex items-center gap-3 p-3 rounded-xl bg-[var(--bg2)]"><div class="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0" style="background:' + col + '14;color:' + col + '"><i class="fa-solid ' + icon + '"></i></div><div class="flex-1 min-w-0"><div class="font-medium text-sm truncate">' + esc(r.name) + (r.autopay ? ' <span class="badge badge-on text-[9px]">auto</span>' : '') + '</div><div class="text-[11px] text-[var(--muted)] capitalize">' + esc(r.freq) + ' &middot; ' + esc(r.cat) + ' &middot; <span style="color:' + dueCol + '">' + due + '</span></div></div><div class="text-sm font-bold whitespace-nowrap" style="color:' + col + '">' + (isBill ? '-' : '+') + money(r.amount) + '</div><button class="btn btn-sm btn-secondary" onclick="payRecurring(' + r.id + ')">' + (isBill ? 'Pay' : 'Post') + '</button><button class="text-[var(--muted)] hover:text-[var(--red)] text-xs" onclick="deleteRecurring(' + r.id + ')" aria-label="Remove ' + esc(r.name) + '"><i class="fa-solid fa-xmark"></i></button></div>'; }

export function debtCard(d) { var meta = debtMeta[d.kind] || debtMeta.personal; var isCard = d.kind === 'credit_card' || !!d.limit; var util = isCard && d.limit ? Math.min(100, Math.round(d.balance / d.limit * 100)) : null; var dd = new Date(d.due + 'T00:00:00'); var days = Math.round((dd - new Date(CY, CM, CD)) / 86400000); var dueTxt = isNaN(days) ? '' : days < 0 ? 'Overdue' : days === 0 ? 'Due today' : 'Due in ' + days + 'd'; var dueCol = days <= 0 ? 'var(--red)' : days <= 5 ? 'var(--amber)' : 'var(--muted)'; return '<div class="p-4 rounded-xl border border-[var(--border)]" style="background:var(--bg2)"><div class="flex items-center gap-3 mb-3"><div class="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0" style="background:' + meta.color + '18;color:' + meta.color + '"><i class="fa-solid ' + meta.icon + '"></i></div><div class="flex-1 min-w-0"><div class="font-semibold text-sm truncate">' + esc(d.name) + '</div><div class="text-[10px] text-[var(--muted)]">' + meta.label + ' &middot; ' + esc(String(d.apr)) + '% APR</div></div><div class="text-right"><div class="text-lg font-bold" style="color:' + meta.color + '">' + money(d.balance) + '</div><div class="text-[10px] text-[var(--muted)]">balance</div></div></div>' + (util != null ? '<div class="prog-bar mb-1"><div class="prog-fill" style="width:' + util + '%;background:' + (util > 70 ? 'var(--red)' : util > 30 ? 'var(--amber)' : 'var(--accent)') + '"></div></div><div class="flex justify-between text-[10px] text-[var(--muted)] mb-3"><span>' + util + '% of ' + money(d.limit) + '</span><span>' + money(Math.max(0, d.limit - d.balance)) + ' available</span></div>' : '<div class="mb-3"></div>') + '<div class="flex items-center justify-between"><div class="text-[11px] text-[var(--muted)]">Min ' + money(d.minPayment) + (dueTxt ? ' &middot; <span style="color:' + dueCol + '">' + dueTxt + '</span>' : '') + '</div><div class="flex gap-2 items-center"><button class="btn btn-sm btn-primary" onclick="openPayDebt(' + d.id + ')">Pay</button><button class="text-[var(--muted)] hover:text-[var(--red)] text-xs" onclick="deleteDebt(' + d.id + ')" aria-label="Remove ' + esc(d.name) + '"><i class="fa-solid fa-trash-can"></i></button></div></div></div>'; }

// ---- option-list helpers (shared by the add/edit modals) ----
export function roomOpts(sel) { return (S.rooms || []).map(function (r) { return '<option value="' + esc(r.id) + '"' + (r.id === sel ? ' selected' : '') + '>' + esc(r.name) + '</option>'; }).join(''); }
export function iconOpts(list, sel) { return list.map(function (i) { return '<option value="' + i + '"' + (i === sel ? ' selected' : '') + '>' + i.replace('fa-', '').replace(/-/g, ' ') + '</option>'; }).join(''); }
