// View layer: builds each screen's HTML and drives navigation + charts.
import {
  S, esc, avatar, money, fd, ds, CY, CM, CD, gm, cu, ia,
  txInMonth, sumType, totalDebt, totalMinPay, emptyState, charts, enhanceA11y, showToast
} from './core.js';
import { catColors, statusIcons, dayNames, ART } from './constants.js';
import {
  statCard, evtRow, txRow, memberCard, lightCard, lockRow, deviceCard, sensorRow,
  camCard, choreRow, shopRow, budgetCard, savingsCard, recurringCard, debtCard
} from './components.js';
import { startCameras, stopCameras, renderNotifPanel } from './actions.js';
import { rAutomations } from './automations.js';
import { rCctv, initCctv } from './cctv.js';
import { persist } from './api.js';

var VIEWS = [
  { id: 'dashboard', icon: 'fa-gauge-high', label: 'Dashboard' },
  { id: 'schedule', icon: 'fa-calendar', label: 'Schedule' },
  { id: 'finance', icon: 'fa-wallet', label: 'Finance' },
  { id: 'home', icon: 'fa-house-signal', label: 'Smart Home' },
  { id: 'cctv', icon: 'fa-video', label: 'CCTV' },
  { id: 'tasks', icon: 'fa-list-check', label: 'Tasks' }
];
// Smart Home now hosts Automations; Family lives in the avatar account menu.
var TITLES = { dashboard: 'Dashboard', schedule: 'Schedule', finance: 'Finance', home: 'Smart Home', automations: 'Smart Home', cctv: 'Cameras & Storage', tasks: 'Tasks', family: 'Family' };

export function navigate(view) { S.view = view; S.notifOpen = false; stopCameras(); renderNav(); render(); if (window.innerWidth < 768) document.getElementById('sidebar').classList.remove('open'); }
export function toggleSidebar() { document.getElementById('sidebar').classList.toggle('open'); }

export function renderNav() {
  var pending = S.chores.filter(function (c) { return !c.done; }).length;
  var navHtml = ''; var mobHtml = '';
  for (var i = 0; i < VIEWS.length; i++) {
    var v = VIEWS[i]; var act = S.view === v.id ? 'active' : ''; var actCol = S.view === v.id ? 'text-[var(--accent)]' : 'text-[var(--muted)]'; var cur = S.view === v.id ? ' aria-current="page"' : '';
    navHtml += '<div class="nav-item ' + act + '" data-view="' + v.id + '"' + cur + ' onclick="navigate(\'' + v.id + '\')"><i class="fa-solid ' + v.icon + '" aria-hidden="true"></i><span>' + v.label + '</span>' + (v.id === 'tasks' && pending > 0 ? '<span class="nav-badge" style="display:flex">' + pending + '</span>' : '') + '</div>';
    mobHtml += '<button onclick="navigate(\'' + v.id + '\')" class="mob-tab flex flex-col items-center gap-0.5 ' + actCol + ' text-[10px] p-1.5" data-view="' + v.id + '"' + cur + '><i class="fa-solid ' + v.icon + ' text-base" aria-hidden="true"></i>' + v.label + '</button>';
  }
  document.getElementById('nav-list').innerHTML = navHtml;
  document.getElementById('mobile-bar').innerHTML = mobHtml;
  var u = cu();
  document.getElementById('sidebar-user').innerHTML = '<div class="flex items-center gap-3">' + avatar(u) + '<div class="min-w-0 flex-1"><div class="font-semibold text-sm truncate">' + esc(u.name) + '</div><div class="text-[10px] text-[var(--muted)] capitalize">' + esc(u.role) + '</div></div><button class="text-[var(--muted)] hover:text-[var(--red)] transition text-sm" title="Sign out" aria-label="Sign out" onclick="logout()"><i class="fa-solid fa-right-from-bracket"></i></button></div>';
  var sh = '<button id="user-menu-btn" class="user-chip" onclick="toggleUserMenu(event)" aria-haspopup="true" aria-expanded="false" title="Account menu">' + avatar(u, 28, 28, 10, 8) + '<span class="uc-name">' + esc(u.name) + '</span><i class="fa-solid fa-chevron-down uc-chev"></i></button>';
  sh += '<div id="user-menu" class="user-menu" role="menu" aria-label="Account">';
  sh += '<div class="um-head">' + avatar(u, 40, 40, 14, 12) + '<div class="min-w-0"><div class="um-name">' + esc(u.name) + '</div><div class="um-role">' + esc(u.role) + '</div></div></div>';
  if (S.members.length > 1) {
    sh += '<div class="um-section-label">Switch member</div>';
    for (var j = 0; j < S.members.length; j++) { var m = S.members[j]; var on = m.id === S.userId; sh += '<button class="um-item" role="menuitemradio" aria-checked="' + (on ? 'true' : 'false') + '" onclick="switchUser(' + m.id + ')">' + avatar(m, 24, 24, 9, 7) + '<span class="flex-1 truncate">' + esc(m.name) + '</span>' + (on ? '<i class="fa-solid fa-check um-check"></i>' : '') + '</button>'; }
  }
  sh += '<div class="um-divider"></div>';
  sh += '<button class="um-item" role="menuitem" onclick="closeUserMenu();navigate(\'family\')"><i class="fa-solid fa-users um-ic"></i><span>Family</span></button>';
  sh += '<button class="um-item um-danger" role="menuitem" onclick="logout()"><i class="fa-solid fa-right-from-bracket um-ic"></i><span>Sign out</span></button>';
  sh += '</div>';
  document.getElementById('user-switcher').innerHTML = sh;
  enhanceA11y(document.getElementById('nav-list'));
  enhanceA11y(document.getElementById('sidebar-user'));
}
export function switchUser(id) { closeUserMenu(); S.userId = id; renderNav(); render(); showToast('Switched to ' + cu().name, 'info'); }

function _closeUserMenuOnce(ev) { var wrap = document.getElementById('user-switcher'); if (wrap && wrap.contains(ev.target)) return; closeUserMenu(); }
export function closeUserMenu() { var menu = document.getElementById('user-menu'); if (menu) menu.classList.remove('open'); var btn = document.getElementById('user-menu-btn'); if (btn) btn.setAttribute('aria-expanded', 'false'); document.removeEventListener('click', _closeUserMenuOnce); }
export function toggleUserMenu(e) { if (e) e.stopPropagation(); var menu = document.getElementById('user-menu'); if (!menu) return; var open = menu.classList.toggle('open'); var btn = document.getElementById('user-menu-btn'); if (btn) btn.setAttribute('aria-expanded', open ? 'true' : 'false'); if (open) { setTimeout(function () { document.addEventListener('click', _closeUserMenuOnce); }, 0); } else { document.removeEventListener('click', _closeUserMenuOnce); } }

export function render() {
  try {
    var c = document.getElementById('content'); c.className = 'flex-1 overflow-y-auto p-5 view-enter stagger'; var html = '';
    var _pt = document.getElementById('page-title'); if (_pt) _pt.textContent = TITLES[S.view] || 'Dashboard';
    switch (S.view) {
      case 'dashboard': html = rDash(); break;
      case 'schedule': html = rSched(); break;
      case 'finance': html = rFin(); setTimeout(initFinCharts, 60); break;
      case 'automations': S.view = 'home'; /* automations merged into Smart Home */
      case 'home': html = rHome(); setTimeout(function () { initHomeCharts(); startCameras(); }, 80); break;
      case 'cctv': html = rCctv(); setTimeout(initCctv, 40); break;
      case 'tasks': html = rTasks(); break;
      case 'family': html = rFam(); break;
      default: html = rDash();
    }
    c.innerHTML = html; if (S.view === 'dashboard') initCounters(); enhanceA11y(c); renderNotifPanel(); persist();
  } catch (e) {
    document.getElementById('content').innerHTML = '<div class="p-8"><h2 class="text-red-400 font-bold mb-2">Render Error</h2><p class="text-sm text-[var(--muted)]">' + esc(e.message) + '</p></div>';
  }
}

/* ===== Dashboard ===== */
export function rDash() {
  var u = cu(), hr = new Date().getHours(); var greeting = hr < 12 ? 'Good Morning' : hr < 17 ? 'Good Afternoon' : 'Good Evening';
  var todayEvts = S.events.filter(function (e) { return e.date === ds(); });
  var totalInc = S.transactions.filter(function (t) { return t.type === 'income'; }).reduce(function (s, t) { return s + t.amount; }, 0);
  var totalExp = S.transactions.filter(function (t) { return t.type === 'expense'; }).reduce(function (s, t) { return s + t.amount; }, 0); var bal = totalInc - totalExp;
  var lightsOn = S.lights.filter(function (l) { return l.on; }).length; var pendingChores = S.chores.filter(function (c) { return !c.done; }).length; var w = S.weather;
  var h = '<div class="hero"><div class="hero-grid"><div class="hero-copy flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">';
  h += '<div><div class="text-[11px] font-semibold tracking-wide text-[var(--accent)] uppercase mb-1">' + new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }) + '</div><h2 class="text-2xl font-bold">' + greeting + ',<br class="sm:hidden">' + ' <span class="grad-text">' + esc(u.name) + '</span></h2></div>';
  if (w && w.temp != null && w.temp !== '--') {
    h += '<div class="card flex items-center gap-4" style="padding:14px 18px;min-width:260px"><div class="text-3xl" style="color:var(--amber)"><i class="fa-solid ' + esc(w.icon) + '"></i></div><div class="flex-1"><div class="flex items-baseline gap-2"><span class="text-2xl font-bold">' + esc(String(w.temp)) + '°</span><span class="text-xs text-[var(--muted)]">' + esc(w.city) + '</span></div><div class="text-xs text-[var(--muted)]">' + esc(w.cond) + ' &middot; H:' + esc(String(w.hi)) + '° L:' + esc(String(w.lo)) + '°</div></div><div class="flex gap-3">';
    for (var fi = 0; fi < w.forecast.length; fi++) { var f = w.forecast[fi]; h += '<div class="text-center"><div class="text-[10px] text-[var(--muted)]">' + esc(f.day) + '</div><i class="fa-solid ' + esc(f.icon) + ' text-xs my-0.5" style="color:var(--amber)"></i><div class="text-[10px]">' + esc(String(f.hi)) + '°</div></div>'; }
    h += '</div></div>';
  }
  h += '</div><div class="hero-art">' + ART.home() + '</div></div></div>';
  h += '<div class="flex gap-3 mb-5 overflow-x-auto pb-1">'; for (var si = 0; si < S.scenes.length; si++) { var sc = S.scenes[si]; h += '<button class="btn btn-ghost flex-shrink-0" onclick="activateScene(\'' + esc(sc.id) + '\')"><i class="fa-solid ' + esc(sc.icon) + '" style="color:' + esc(sc.color) + '"></i>' + esc(sc.name) + '</button>'; } h += '</div>';
  h += '<div class="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">';
  h += statCard('emerald', 'fa-calendar-check', 'var(--accent)', 'Today\'s Events', '<span class="counter" data-target="' + todayEvts.length + '">0</span>', '');
  h += statCard('amber', 'fa-wallet', 'var(--amber)', 'Balance', '<span class="grad-text counter" data-target="' + bal + '" data-prefix="$">$0</span>', '');
  h += statCard('cyan', 'fa-lightbulb', 'var(--cyan)', 'Home', lightsOn + ' lights &middot; <span class="badge ' + (S.securityArmed ? 'badge-armed' : 'badge-unlocked') + ' text-[10px]">' + (S.securityArmed ? 'Armed' : 'Off') + '</span>', '');
  h += statCard('purple', 'fa-list-check', 'var(--purple)', 'Pending', '<span class="counter" data-target="' + pendingChores + '">0</span>', 'chores left');
  h += '</div>';
  h += '<div class="grid grid-cols-1 lg:grid-cols-3 gap-5"><div class="card lg:col-span-2"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold">Upcoming Events</h3><button class="btn btn-sm btn-primary" onclick="openAddEvent()"><i class="fa-solid fa-plus"></i>Add</button></div><div class="space-y-1.5">';
  var upEvts = S.events.filter(function (e) { return e.date >= ds(); }).sort(function (a, b) { return a.date.localeCompare(b.date) || a.time.localeCompare(b.time); }).slice(0, 5);
  if (upEvts.length) { for (var ei = 0; ei < upEvts.length; ei++) { h += evtRow(upEvts[ei]); } } else { h += emptyState('var(--accent)', 'No upcoming events', 'Tap Add to plan something together'); } h += '</div></div>';
  h += '<div class="space-y-5"><div class="card"><h3 class="font-semibold mb-3">Family</h3>'; for (var mi = 0; mi < S.members.length; mi++) { var m = S.members[mi]; h += '<div class="flex items-center gap-2.5 py-1.5">' + avatar(m, 30, 30, 10, 8) + '<div class="flex-1 min-w-0"><div class="text-sm font-medium">' + esc(m.name) + '</div><div class="text-[10px] text-[var(--muted)] capitalize"><i class="fa-solid ' + (statusIcons[m.status] || 'fa-circle') + ' text-[8px]"></i> ' + esc(m.status) + '</div></div><span class="badge ' + (m.role === 'admin' ? 'badge-admin' : 'badge-member') + ' text-[10px]">' + esc(m.role) + '</span></div>'; } h += '</div>';
  h += '<div class="card"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm">Chore Points</h3><button class="text-xs text-[var(--accent)] hover:underline" onclick="navigate(\'tasks\')">View All</button></div>'; for (var pi = 0; pi < S.members.length; pi++) { var pm = S.members[pi]; var pts = S.chorePoints[pm.id] || 0; h += '<div class="flex items-center gap-2 mb-2">' + avatar(pm, 22, 22, 8, 6) + '<div class="flex-1"><div class="prog-bar"><div class="prog-fill" style="width:' + Math.min(100, pts) + '%;background:' + esc(pm.color) + '"></div></div></div><span class="text-xs font-bold" style="color:' + esc(pm.color) + '">' + pts + '</span></div>'; } h += '</div>';
  var dueSoon = (S.recurring || []).map(function (r) { return { r: r, d: Math.round((new Date(r.next + 'T00:00:00') - new Date(CY, CM, CD)) / 86400000) }; }).filter(function (x) { return x.r.kind !== 'income' && x.d <= 7; }).sort(function (a, b) { return a.d - b.d; });
  if (dueSoon.length) { h += '<div class="card"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm"><i class="fa-solid fa-file-invoice-dollar mr-1 text-[var(--amber)]"></i>Bills Due Soon</h3><button class="text-xs text-[var(--accent)] hover:underline" onclick="navigate(\'finance\')">All</button></div>'; for (var bsi = 0; bsi < Math.min(4, dueSoon.length); bsi++) { var bd = dueSoon[bsi].r, bdd = dueSoon[bsi].d; var lbl = bdd < 0 ? 'Overdue' : bdd === 0 ? 'Today' : bdd === 1 ? 'Tomorrow' : bdd + 'd'; var lc = bdd <= 0 ? 'var(--red)' : bdd <= 3 ? 'var(--amber)' : 'var(--muted)'; h += '<div class="flex items-center gap-2 py-1.5"><div class="flex-1 min-w-0"><div class="text-sm font-medium truncate">' + esc(bd.name) + '</div><div class="text-[10px]" style="color:' + lc + '">' + lbl + '</div></div><span class="text-sm font-bold text-[var(--red)]">' + money(bd.amount) + '</span><button class="btn btn-sm btn-secondary" onclick="payRecurring(' + bd.id + ')">Pay</button></div>'; } h += '</div>'; }
  h += '</div></div>';
  h += '<div class="card mt-5"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold">Budget Overview</h3><button class="text-xs text-[var(--accent)] hover:underline" onclick="navigate(\'finance\')">Details</button></div><div class="grid grid-cols-2 sm:grid-cols-3 gap-3">'; for (var bi = 0; bi < S.budgets.length; bi++) { h += budgetCard(S.budgets[bi]); } h += '</div></div>'; return h;
}
export function initCounters() { document.querySelectorAll('.counter').forEach(function (el) { var t = +el.dataset.target, p = el.dataset.prefix || ''; var c = 0; var s = Math.max(1, Math.ceil(t / 35)); var timer = setInterval(function () { c += s; if (c >= t) { c = t; clearInterval(timer); } el.textContent = p + c.toLocaleString(); }, 25); }); }

/* ===== Schedule ===== */
export function rSched() {
  var y = S.calYear, m = S.calMonth, firstDay = new Date(y, m, 1).getDay(), daysInMonth = new Date(y, m + 1, 0).getDate();
  var mNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  var h = '<div class="flex flex-col lg:flex-row gap-5"><div class="flex-1"><div class="card"><div class="flex items-center justify-between mb-4"><button class="btn btn-sm btn-secondary" onclick="changeMonth(-1)" aria-label="Previous month"><i class="fa-solid fa-chevron-left"></i></button><h3 class="font-semibold text-lg">' + mNames[m] + ' ' + y + '</h3><button class="btn btn-sm btn-secondary" onclick="changeMonth(1)" aria-label="Next month"><i class="fa-solid fa-chevron-right"></i></button></div><div class="cal-grid">';
  for (var di = 0; di < 7; di++) { h += '<div class="cal-head">' + dayNames[di] + '</div>'; } for (var ei = 0; ei < firstDay; ei++) { h += '<div class="cal-day empty"></div>'; }
  for (var d = 1; d <= daysInMonth; d++) { var ds2 = y + '-' + String(m + 1).padStart(2, '0') + '-' + String(d).padStart(2, '0'); var isToday = d === CD && m === CM && y === CY; var isSel = ds2 === S.selectedDate; var dev = S.events.filter(function (e) { return e.date === ds2; });
    h += '<div class="cal-day ' + (isToday ? 'today' : '') + ' ' + (isSel ? 'selected' : '') + '" onclick="selectDate(\'' + ds2 + '\')" aria-label="' + ds2 + (dev.length ? ', ' + dev.length + ' events' : '') + '"><span class="day-num">' + d + '</span>'; if (dev.length) { h += '<div class="flex flex-wrap gap-0.5 mt-0.5">'; for (var dj = 0; dj < dev.length; dj++) { h += '<span class="evt-dot" style="background:' + (catColors[dev[dj].cat] || '#6B7B8D') + '"></span>'; } h += '</div>'; } h += '</div>'; }
  h += '</div></div></div>'; var selEvts = S.events.filter(function (e) { return e.date === S.selectedDate; }).sort(function (a, b) { return a.time.localeCompare(b.time); });
  h += '<div class="lg:w-72"><div class="card"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm">' + fd(S.selectedDate) + '</h3><button class="btn btn-sm btn-primary" onclick="openAddEvent()" aria-label="Add event"><i class="fa-solid fa-plus"></i></button></div>';
  if (selEvts.length) { for (var si = 0; si < selEvts.length; si++) { var se = selEvts[si]; var sm2 = gm(se.memberId); h += '<div class="p-2.5 rounded-xl mb-1.5 cursor-pointer hover:bg-[var(--surface2)] transition" style="border-left:3px solid ' + (catColors[se.cat] || '#6B7B8D') + '" onclick="viewEvent(' + se.id + ')"><div class="font-medium text-sm">' + esc(se.title) + '</div><div class="text-[11px] text-[var(--muted)]"><i class="fa-regular fa-clock"></i> ' + esc(se.time) + '</div><div class="flex items-center gap-1.5 mt-1">' + avatar(sm2, 18, 18, 7, 5) + '<span class="text-[10px] text-[var(--muted)]">' + esc(sm2 ? sm2.name : '') + '</span></div></div>'; } } else { h += emptyState('var(--amber)', 'No events', 'Nothing scheduled for this day'); } h += '</div></div></div>'; return h;
}
export function selectDate(d) { S.selectedDate = d; render(); }
export function changeMonth(d) { S.calMonth += d; if (S.calMonth > 11) { S.calMonth = 0; S.calYear++; } if (S.calMonth < 0) { S.calMonth = 11; S.calYear--; } render(); }

/* ===== Finance ===== */
export function rFin() {
  var mt = txInMonth(CY, CM); var inc = sumType(mt, 'income'), exp = sumType(mt, 'expense');
  var bal = sumType(S.transactions, 'income') - sumType(S.transactions, 'expense');
  var debt = totalDebt(); var billsDue = (S.recurring || []).filter(function (r) { return r.kind !== 'income'; }).reduce(function (s, r) { return s + (+r.amount || 0); }, 0);
  var h = '<div class="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">'; h += statCard('emerald', 'fa-wallet', 'var(--accent)', 'Balance', '<span class="grad-text">' + money(bal) + '</span>', '');
  h += statCard('amber', 'fa-arrow-down', 'var(--accent)', 'Income', '+' + money(inc), 'this month'); h += statCard('red', 'fa-arrow-up', 'var(--red)', 'Expenses', '-' + money(exp), 'this month'); h += statCard('purple', 'fa-scale-unbalanced', 'var(--purple)', 'Total Debt', money(debt), (S.debts || []).length + ' accounts'); h += '</div>';
  h += '<div class="card mb-5"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold">Monthly Budgets</h3><button class="btn btn-sm btn-primary" onclick="openAddBudget()" aria-label="Add budget"><i class="fa-solid fa-plus"></i></button></div>' + (S.budgets.length ? '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">' : '') + ''; for (var bi = 0; bi < S.budgets.length; bi++) { h += budgetCard(S.budgets[bi]); } h += (S.budgets.length ? '</div>' : emptyState('var(--accent)', 'No budgets yet', 'Set a monthly limit to track spending')) + '</div>';
  h += '<div class="card mb-5"><div class="flex items-center justify-between mb-4"><div><h3 class="font-semibold">Bills &amp; Recurring</h3><p class="text-[11px] text-[var(--muted)]">' + money(billsDue) + ' in recurring bills</p></div><button class="btn btn-sm btn-primary" onclick="openAddRecurring()"><i class="fa-solid fa-plus"></i>Add</button></div>'; var recs = (S.recurring || []).slice().sort(function (a, b) { return (a.next || '').localeCompare(b.next || ''); }); if (recs.length) { h += '<div class="space-y-2">'; for (var ri2 = 0; ri2 < recs.length; ri2++) { h += recurringCard(recs[ri2]); } h += '</div>'; } else { h += emptyState('var(--blue)', 'No recurring items yet', 'Add bills or income that repeat'); } h += '</div>';
  h += '<div class="card mb-5"><div class="flex items-center justify-between mb-4"><div><h3 class="font-semibold">Debts &amp; Credit Cards</h3><p class="text-[11px] text-[var(--muted)]">' + money(debt) + ' owed &middot; ' + money(totalMinPay()) + '/mo minimum</p></div><button class="btn btn-sm btn-primary" onclick="openAddDebt()"><i class="fa-solid fa-plus"></i>Add</button></div>'; var dbs = (S.debts || []).slice().sort(function (a, b) { return (b.balance || 0) - (a.balance || 0); }); if (dbs.length) { h += '<div class="grid grid-cols-1 sm:grid-cols-2 gap-3">'; for (var dbi = 0; dbi < dbs.length; dbi++) { h += debtCard(dbs[dbi]); } h += '</div>'; } else { h += emptyState('var(--purple)', 'No debts tracked — nice!', 'You are all clear here'); } h += '</div>';
  h += '<div class="card mb-5"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold">Savings Goals</h3><button class="btn btn-sm btn-primary" onclick="openAddSavings()" aria-label="Add savings goal"><i class="fa-solid fa-plus"></i></button></div>' + (S.savings.length ? '<div class="grid grid-cols-1 sm:grid-cols-3 gap-4">' : '') + ''; for (var si = 0; si < S.savings.length; si++) { h += savingsCard(S.savings[si]); } h += (S.savings.length ? '</div>' : emptyState('var(--cyan)', 'No savings goals yet', 'Start a goal and watch it grow')) + '</div>';
  h += '<div class="grid grid-cols-1 lg:grid-cols-2 gap-5 mb-5"><div class="card"><h3 class="font-semibold mb-3">Monthly Overview</h3><canvas id="chart-bar" height="200"></canvas></div><div class="card"><h3 class="font-semibold mb-3">Expense Breakdown</h3><canvas id="chart-dough" height="200"></canvas></div></div>';
  h += '<div class="card"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold">Transactions</h3><button class="btn btn-primary btn-sm" onclick="openAddTransaction()"><i class="fa-solid fa-plus"></i>Add</button></div>'; var revTx = S.transactions.slice().reverse(); for (var ti = 0; ti < revTx.length; ti++) { h += txRow(revTx[ti]); } h += '</div>'; return h;
}
export function initFinCharts() {
  var Chart = window.Chart; if (!Chart) return;
  var months = [], incD = [], expD = []; for (var i = 5; i >= 0; i--) { var d = new Date(CY, CM - i, 1); months.push(d.toLocaleString('en', { month: 'short' })); var mt = txInMonth(d.getFullYear(), d.getMonth()); incD.push(sumType(mt, 'income')); expD.push(sumType(mt, 'expense')); }
  if (charts.bar) charts.bar.destroy(); var b = document.getElementById('chart-bar'); if (b) charts.bar = new Chart(b, { type: 'bar', data: { labels: months, datasets: [{ label: 'Income', data: incD, backgroundColor: 'rgba(16,185,129,.65)', borderRadius: 5, borderSkipped: false }, { label: 'Expenses', data: expD, backgroundColor: 'rgba(239,68,68,.65)', borderRadius: 5, borderSkipped: false }] }, options: { responsive: true, plugins: { legend: { labels: { color: '#94A3B8', font: { family: 'Plus Jakarta Sans', size: 11 } } } }, scales: { x: { ticks: { color: '#7B8CA8' }, grid: { color: 'rgba(45,59,85,.2)' } }, y: { ticks: { color: '#7B8CA8', callback: function (v) { return '$' + v; } }, grid: { color: 'rgba(45,59,85,.2)' } } } } });
  var expByCat = {}; S.transactions.filter(function (t) { return t.type === 'expense'; }).forEach(function (t) { expByCat[t.cat] = (expByCat[t.cat] || 0) + t.amount; }); var dc = ['#10B981', '#F59E0B', '#EF4444', '#3B82F6', '#8B5CF6', '#EC4899', '#06B6D4', '#F97316', '#6B7280'];
  if (charts.dough) charts.dough.destroy(); var dd = document.getElementById('chart-dough'); if (dd) charts.dough = new Chart(dd, { type: 'doughnut', data: { labels: Object.keys(expByCat), datasets: [{ data: Object.values(expByCat), backgroundColor: dc.slice(0, Object.keys(expByCat).length), borderWidth: 0 }] }, options: { responsive: true, cutout: '62%', plugins: { legend: { position: 'right', labels: { color: '#94A3B8', padding: 10, font: { family: 'Plus Jakarta Sans', size: 11 } } } } } });
}

/* ===== Smart Home ===== */
export function rHome() {
  var rm = S.homeRoom; var fL = rm === 'all' ? S.lights : S.lights.filter(function (l) { return l.room === rm; }); var fD = rm === 'all' ? S.devices : S.devices.filter(function (d) { return d.room === rm; }); var locks = fD.filter(function (d) { return d.type === 'lock'; }); var sensors = fD.filter(function (d) { return d.type === 'sensor'; }); var others = fD.filter(function (d) { return ['lock', 'camera', 'sensor'].indexOf(d.type) === -1; }); var t = S.thermostat, pct = t.on ? Math.min(100, Math.max(0, ((t.target - 55) / 30) * 100)) : 0; var lightsOn = S.lights.filter(function (l) { return l.on; }).length; var devOn = S.devices.filter(function (d) { return ['lock', 'sensor'].indexOf(d.type) === -1 && d.status !== 'off' && d.status !== 'inactive'; }).length;
  var h = '<div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"><div><h3 class="text-xl font-bold">Smart Home</h3><p class="text-sm text-[var(--muted)]">' + (S.devices.length + S.lights.length) + ' devices &middot; ' + S.rooms.length + ' rooms</p></div><div class="flex gap-2 flex-wrap"><button class="btn btn-sm btn-secondary" onclick="openVoicePanel()"><i class="fa-solid fa-microphone-lines"></i><span class="hidden sm:inline">Voice</span></button><button class="btn btn-sm btn-secondary" onclick="openConnectDevices()"><i class="fa-solid fa-wifi"></i><span class="hidden sm:inline">Connect Devices</span></button><button class="btn btn-sm btn-secondary" onclick="openAddRoom()"><i class="fa-solid fa-door-open"></i><span class="hidden sm:inline">Room</span></button><button class="btn btn-sm btn-primary" onclick="openAddDevice()"><i class="fa-solid fa-plus"></i>Add Device</button></div></div>';
  h += '<div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-5">'; h += statCard('cyan', 'fa-lightbulb', 'var(--amber)', 'Lights', lightsOn + '<span class="text-xs font-normal text-[var(--muted)]">/' + S.lights.length + '</span>', ''); h += statCard('emerald', 'fa-plug', 'var(--accent)', 'Devices', devOn + '<span class="text-xs font-normal text-[var(--muted)]"> active</span>', ''); h += statCard('red', 'fa-shield-halved', 'var(--red)', 'Security', '<span class="badge ' + (S.securityArmed ? 'badge-armed' : 'badge-unlocked') + ' text-[10px]">' + (S.securityArmed ? 'Armed' : 'Off') + '</span>', ''); h += statCard('amber', 'fa-bolt', 'var(--amber)', 'Energy', S.energy.today + '<span class="text-xs font-normal text-[var(--muted)]"> kWh</span>', ''); h += '</div>';
  var allCams = S.devices.filter(function (d) { return d.type === 'camera'; });
  if (allCams.length) { h += '<div class="card mb-5"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm"><i class="fa-solid fa-video mr-1 text-[var(--blue)]"></i>Security Cameras <span class="text-[var(--muted)] font-normal">(' + allCams.length + ')</span></h3><button class="btn btn-sm btn-secondary" onclick="openAddDevice()"><i class="fa-solid fa-plus"></i>Add Camera</button></div><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">'; for (var cci = 0; cci < allCams.length; cci++) { h += camCard(allCams[cci]); } h += '</div></div>'; }
  h += '<div class="mb-5"><h3 class="font-semibold mb-3">Quick Scenes</h3><div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">'; for (var si = 0; si < S.scenes.length; si++) { var sc = S.scenes[si]; h += '<div class="scene-card" onclick="activateScene(\'' + esc(sc.id) + '\')"><div class="scene-icon" style="background:' + esc(sc.color) + '18;color:' + esc(sc.color) + '"><i class="fa-solid ' + esc(sc.icon) + '"></i></div><div class="font-semibold text-sm">' + esc(sc.name) + '</div><div class="text-[10px] text-[var(--muted)] mt-1">' + esc(sc.desc) + '</div></div>'; } h += '</div></div>';
  h += '<div class="flex gap-2 mb-5 overflow-x-auto pb-1">'; var allRooms = [{ id: 'all', name: 'All Rooms', icon: 'fa-house-chimney' }].concat(S.rooms); for (var ri = 0; ri < allRooms.length; ri++) { var r = allRooms[ri]; h += '<div class="room-tab ' + (rm === r.id ? 'active' : '') + '" onclick="setRoom(\'' + esc(r.id) + '\')"><i class="fa-solid ' + esc(r.icon) + ' mr-1"></i>' + esc(r.name) + '</div>'; } h += '</div>';
  h += '<div class="grid grid-cols-1 lg:grid-cols-3 gap-5 mb-5">';
  h += '<div class="card text-center"><h3 class="font-semibold mb-3 text-sm"><i class="fa-solid fa-temperature-half mr-1 text-[var(--amber)]"></i>Climate</h3><div class="thermo-ring" style="--pct:' + pct + '"><div class="thermo-inner"><div class="thermo-temp">' + (t.on ? t.target : '--') + '°</div><div class="thermo-label">' + (t.on ? esc(t.mode) : 'off') + '</div></div></div><div class="flex items-center justify-center gap-3 mt-3 mb-3"><button class="w-9 h-9 rounded-xl flex items-center justify-center bg-[var(--surface2)] hover:bg-[var(--border)] transition text-base font-bold" onclick="adjTemp(-1)" aria-label="Lower temperature">-</button><div class="toggle ' + (t.on ? 'on amber' : '') + '" onclick="toggleThermo()" aria-label="Toggle climate"></div><button class="w-9 h-9 rounded-xl flex items-center justify-center bg-[var(--surface2)] hover:bg-[var(--border)] transition text-base font-bold" onclick="adjTemp(1)" aria-label="Raise temperature">+</button></div><div class="flex justify-center gap-1.5">'; var modes = ['cool', 'heat', 'auto']; for (var mi2 = 0; mi2 < modes.length; mi2++) { var md = modes[mi2]; h += '<button class="btn btn-sm ' + (t.mode === md && t.on ? 'btn-primary' : 'btn-ghost') + '" onclick="setThermoMode(\'' + md + '\')">' + md.charAt(0).toUpperCase() + md.slice(1) + '</button>'; } h += '</div><div class="text-[10px] text-[var(--muted)] mt-2">Current: ' + esc(String(t.temp)) + '°F</div></div>';
  h += '<div class="card"><h3 class="font-semibold text-sm mb-3"><i class="fa-solid fa-bolt mr-1 text-[var(--amber)]"></i>Energy</h3><canvas id="chart-energy" height="170"></canvas><div class="grid grid-cols-3 gap-2 mt-3 text-center"><div><div class="text-base font-bold">' + S.energy.today + '</div><div class="text-[9px] text-[var(--muted)]">Today</div></div><div><div class="text-base font-bold">' + S.energy.week + '</div><div class="text-[9px] text-[var(--muted)]">Week</div></div><div><div class="text-base font-bold">' + S.energy.month + '</div><div class="text-[9px] text-[var(--muted)]">Month</div></div></div></div>';
  h += '<div class="card"><h3 class="font-semibold text-sm mb-3"><i class="fa-solid fa-chart-pie mr-1 text-[var(--cyan)]"></i>Breakdown</h3><canvas id="chart-edough" height="170"></canvas><div class="space-y-1.5 mt-2">'; for (var eei = 0; eei < S.energy.items.length; eei++) { var it = S.energy.items[eei]; h += '<div class="flex items-center gap-2 text-xs"><div class="w-2.5 h-2.5 rounded" style="background:' + esc(it.color) + '"></div><span class="flex-1">' + esc(it.cat) + '</span><span class="font-semibold">' + it.pct + '%</span></div>'; } h += '</div></div></div>';
  h += '<div class="card mb-5 ' + (fL.some(function (l) { return l.on; }) ? 'light-on' : '') + '"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm"><i class="fa-solid fa-lightbulb mr-1 text-[var(--amber)]"></i>Lights</h3><div class="flex gap-2"><button class="btn btn-sm btn-ghost" onclick="allLights(true)">All On</button><button class="btn btn-sm btn-ghost" onclick="allLights(false)">All Off</button></div></div>' + (fL.length ? '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">' : ''); for (var li = 0; li < fL.length; li++) { h += lightCard(fL[li]); } h += (fL.length ? '</div>' : emptyState('var(--amber)', 'No lights here yet', 'Add a light or connect WiFi devices')) + '</div>';
  h += '<div class="grid grid-cols-1 lg:grid-cols-2 gap-5 mb-5"><div class="card"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm"><i class="fa-solid fa-lock mr-1 text-[var(--accent)]"></i>Security</h3><div class="flex items-center gap-2"><span class="text-[10px] text-[var(--muted)]">Arm</span><div class="toggle ' + (S.securityArmed ? 'on' : '') + '" style="width:40px;height:22px" onclick="toggleArm()" aria-label="Arm security"></div></div></div><div class="space-y-2">'; for (var lki = 0; lki < locks.length; lki++) { h += lockRow(locks[lki]); } h += '</div>'; if (sensors.length) { h += '<h4 class="font-semibold text-xs mt-3 mb-2"><i class="fa-solid fa-satellite-dish mr-1 text-[var(--cyan)]"></i>Sensors</h4><div class="space-y-1.5">'; for (var sni = 0; sni < sensors.length; sni++) { h += sensorRow(sensors[sni]); } h += '</div>'; } h += '</div>';
  h += '<div class="card"><h3 class="font-semibold text-sm mb-3"><i class="fa-solid fa-plug mr-1 text-[var(--accent)]"></i>Devices</h3>' + (others.length ? '<div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5">' : ''); for (var di2 = 0; di2 < others.length; di2++) { h += deviceCard(others[di2]); } h += (others.length ? '</div>' : emptyState('var(--accent)', 'No devices here yet', 'Tap Connect Devices to scan your WiFi')) + '</div></div>';
  h += '<div class="card"><h3 class="font-semibold text-sm mb-3"><i class="fa-solid fa-bell mr-1 text-[var(--amber)]"></i>Activity</h3>'; var sevColors = { info: 'var(--blue)', warning: 'var(--amber)', success: 'var(--accent)', danger: 'var(--red)' }; for (var ai = 0; ai < Math.min(6, S.alerts.length); ai++) { var a = S.alerts[ai]; h += '<div class="alert-line"><div class="w-2 h-2 rounded-full mt-1.5 flex-shrink-0" style="background:' + sevColors[a.sev] + '"></div><div class="flex-1"><div class="text-xs">' + esc(a.msg) + '</div><div class="text-[10px] text-[var(--muted)]">' + esc(a.time) + '</div></div></div>'; } h += '</div>';
  h += rAutomations();
  return h;
}
export function initHomeCharts() {
  var Chart = window.Chart; if (!Chart) return;
  var days = [], usage = []; var wk = +S.energy.week || 0; var weights = [1.05, 0.95, 1.0, 1.0, 1.1, 1.2, 0.9]; var wsum = weights.reduce(function (a, b) { return a + b; }, 0); for (var i = 6; i >= 0; i--) { var d = new Date(CY, CM, CD - i); days.push(d.toLocaleString('en', { weekday: 'short' })); var idx = d.getDay(); usage.push(wk ? Math.round(wk / wsum * weights[idx] * 10) / 10 : 0); } usage[6] = +S.energy.today || usage[6];
  if (charts.energy) charts.energy.destroy(); var e = document.getElementById('chart-energy'); if (e) charts.energy = new Chart(e, { type: 'bar', data: { labels: days, datasets: [{ label: 'kWh', data: usage, backgroundColor: 'rgba(245,158,11,.55)', borderRadius: 5, borderSkipped: false }] }, options: { responsive: true, plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#7B8CA8', font: { size: 10 } }, grid: { display: false } }, y: { ticks: { color: '#7B8CA8', font: { size: 10 } }, grid: { color: 'rgba(45,59,85,.2)' } } } } });
  if (charts.edough) charts.edough.destroy(); var ed = document.getElementById('chart-edough'); if (ed) charts.edough = new Chart(ed, { type: 'doughnut', data: { labels: S.energy.items.map(function (i) { return i.cat; }), datasets: [{ data: S.energy.items.map(function (i) { return i.pct; }), backgroundColor: S.energy.items.map(function (i) { return i.color; }), borderWidth: 0 }] }, options: { responsive: true, cutout: '68%', plugins: { legend: { display: false } } } });
}

/* ===== Tasks ===== */
export function rTasks() { var tab = S.tasksTab; var pendingChores = S.chores.filter(function (c) { return !c.done; }).length; var checkedShop = S.shopping.filter(function (s) { return s.checked; }).length; var h = '<div class="flex gap-2 mb-5"><div class="sec-tab ' + (tab === 'chores' ? 'active' : '') + '" onclick="S.tasksTab=\'chores\';render()"><i class="fa-solid fa-broom mr-1"></i>Chores (' + pendingChores + ')</div><div class="sec-tab ' + (tab === 'shopping' ? 'active' : '') + '" onclick="S.tasksTab=\'shopping\';render()"><i class="fa-solid fa-cart-shopping mr-1"></i>Shopping (' + (S.shopping.length - checkedShop) + ')</div></div>'; h += tab === 'chores' ? rChores() : rShopping(); return h; }
export function rChores() { var myChores = S.chores.filter(function (c) { return c.assignee === S.userId; }); var allChores = ia() ? S.chores : myChores; var h = '<div class="card mb-5"><h3 class="font-semibold text-sm mb-3"><i class="fa-solid fa-trophy mr-1 text-[var(--amber)]"></i>Chore Points</h3><div class="grid grid-cols-2 sm:grid-cols-4 gap-3">'; for (var mi = 0; mi < S.members.length; mi++) { var m = S.members[mi]; var pts = S.chorePoints[m.id] || 0; h += '<div class="text-center p-3 rounded-xl border border-[var(--border)]" style="background:var(--bg2)">' + avatar(m, 32, 32, 11, 9) + '<div class="font-semibold text-xs mt-1.5">' + esc(m.name) + '</div><div class="text-lg font-bold" style="color:' + esc(m.color) + '">' + pts + '</div><div class="text-[9px] text-[var(--muted)]">points</div></div>'; } h += '</div></div><div class="card"><div class="flex items-center justify-between mb-3"><h3 class="font-semibold text-sm">This Week\'s Chores</h3><button class="btn btn-sm btn-primary" onclick="openAddChore()"><i class="fa-solid fa-plus"></i>Add</button></div>' + (allChores.length ? '<div class="space-y-2">' : ''); for (var ci = 0; ci < allChores.length; ci++) { h += choreRow(allChores[ci]); } h += (allChores.length ? '</div>' : emptyState('var(--accent)', 'No chores yet', 'Add a chore to start earning points')) + '</div>'; return h; }
export function rShopping() { var h = '<div class="card"><div class="flex items-center justify-between mb-4"><h3 class="font-semibold text-sm">Shopping List</h3><button class="btn btn-sm btn-primary" onclick="openAddShop()"><i class="fa-solid fa-plus"></i>Add</button></div>' + (S.shopping.length ? '<div class="space-y-1">' : ''); for (var si = 0; si < S.shopping.length; si++) { h += shopRow(S.shopping[si]); } var checked = S.shopping.filter(function (s) { return s.checked; }).length; if (checked) { h += '<div class="mt-3 pt-3 border-t border-[var(--border)] text-xs text-[var(--muted)]">' + checked + ' items checked &middot; <button class="text-[var(--red)] hover:underline" onclick="clearChecked()">Remove checked</button></div>'; } h += (S.shopping.length ? '</div>' : emptyState('var(--blue)', 'List is empty', 'Add items the family needs to buy')) + '</div>'; return h; }

/* ===== Family ===== */
export function rFam() {
  var admin = ia();
  var famName = S.householdName || 'Your Family';
  var h = '<div class="card mb-5" style="background:linear-gradient(120deg,rgba(16,185,129,.10),rgba(6,182,212,.04))"><div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div class="flex items-center gap-3 min-w-0"><div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center flex-shrink-0"><i class="fa-solid fa-people-roof text-white text-lg"></i></div><div class="min-w-0"><div class="flex items-center gap-2"><h3 class="text-xl font-bold truncate">' + esc(famName) + '</h3>' + (admin ? '<button class="icon-btn" style="width:30px;height:30px" onclick="openEditFamilyName()" title="Edit family name" aria-label="Edit family name"><i class="fa-solid fa-pen text-xs"></i></button>' : '') + '</div><p class="text-sm text-[var(--muted)]">' + S.members.length + ' member' + (S.members.length === 1 ? '' : 's') + ' &middot; ' + S.members.filter(function (m) { return m.role === 'admin'; }).length + ' admin</p></div></div>' + (admin ? '<button class="btn btn-primary btn-sm flex-shrink-0" onclick="openAddMember()"><i class="fa-solid fa-user-plus"></i>Add Member</button>' : '') + '</div>' + (admin ? '' : '<p class="text-[11px] text-[var(--muted)] mt-3 pt-3 border-t border-[var(--border)]"><i class="fa-solid fa-circle-info mr-1"></i>You can edit your own profile. Ask a household admin to add or remove members.</p>') + '</div>';
  h += '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-5">'; for (var i = 0; i < S.members.length; i++) { h += memberCard(S.members[i]); } h += '</div>'; h += '<div class="card"><h3 class="font-semibold text-lg mb-4">Activity Log</h3>'; var sevColors = { info: 'var(--blue)', warning: 'var(--amber)', success: 'var(--accent)', danger: 'var(--red)' }; for (var ai = 0; ai < Math.min(8, S.alerts.length); ai++) { var a = S.alerts[ai]; h += '<div class="alert-line"><div class="w-2 h-2 rounded-full mt-1.5 flex-shrink-0" style="background:' + sevColors[a.sev] + '"></div><div class="flex-1"><div class="text-sm">' + esc(a.msg) + '</div><div class="text-xs text-[var(--muted)]">' + esc(a.time) + '</div></div></div>'; } h += '</div>'; return h; }
