// Voice control (Web Speech) + the Alexa / Siri / Google command bridge.
// The local intent parser mirrors server/voice.js so in-app voice works offline.
import { S, esc, showToast, showModal, hideModal, val } from './core.js';
import { render } from './views.js';
import { activateScene } from './actions.js';
import { persist } from './api.js';

export function speak(text) { try { if ('speechSynthesis' in window && text) { var u = new SpeechSynthesisUtterance(text); u.rate = 1.03; speechSynthesis.cancel(); speechSynthesis.speak(u); } } catch (e) {} }
function voiceLog(msg, sev, type) { S.alerts.unshift({ id: ++S.nid, type: type || 'voice', msg: msg, time: 'Just now', sev: sev || 'info', seen: false }); }
function findRoomByText(text) { if (/\b(all|everywhere|whole house|the house)\b/.test(text)) return 'all'; for (var i = 0; i < S.rooms.length; i++) { var r = S.rooms[i]; var n = r.name.toLowerCase().replace(/'s/g, ''); if (text.indexOf(n) >= 0 || text.indexOf(r.id) >= 0) return r.id; } return null; }

export function runVoice(raw) {
  var text = (raw || '').toLowerCase().trim(); if (!text) return "I didn't catch that.";
  var sceneAliases = { 'good night': 'bedtime', 'goodnight': 'bedtime', 'go to sleep': 'bedtime', 'bed time': 'bedtime', 'good morning': 'morning', 'wake up': 'morning', 'away mode': 'away', 'leaving home': 'away', 'movie night': 'movie', 'party mode': 'party' };
  var sc = S.scenes.find(function (s) { return text.indexOf(s.name.toLowerCase()) >= 0; });
  if (!sc) { for (var ak in sceneAliases) { if (text.indexOf(ak) >= 0) { sc = S.scenes.find(function (s) { return s.id === sceneAliases[ak]; }); if (sc) break; } } }
  if (!sc && /\b(scene|mode)\b/.test(text)) { sc = S.scenes.find(function (s) { return text.indexOf(s.id) >= 0; }); }
  if (sc) { activateScene(sc.id); return sc.name + ' activated.'; }
  if (/\b(arm|disarm)\b/.test(text) && /\b(security|alarm|system|house)\b/.test(text)) { S.securityArmed = /\barm\b/.test(text) && !/\bdisarm\b/.test(text); voiceLog('Security ' + (S.securityArmed ? 'armed' : 'disarmed') + ' by voice', S.securityArmed ? 'success' : 'warning', 'system'); render(); return 'Security ' + (S.securityArmed ? 'armed' : 'disarmed') + '.'; }
  if (/\b(lock|unlock)\b/.test(text)) { var lock = /\block\b/.test(text) && !/\bunlock\b/.test(text); var targets = S.devices.filter(function (d) { return d.type === 'lock'; }); if (!/\b(all|every|doors)\b/.test(text)) { var named = targets.filter(function (d) { return text.indexOf(d.name.toLowerCase()) >= 0; }); if (named.length) targets = named; } targets.forEach(function (d) { d.status = lock ? 'locked' : 'unlocked'; d.icon = lock ? 'fa-lock' : 'fa-lock-open'; }); voiceLog(targets.length + ' lock(s) ' + (lock ? 'locked' : 'unlocked') + ' by voice', 'info', 'door'); render(); return (targets.length === 1 ? targets[0].name : targets.length + ' doors') + ' ' + (lock ? 'locked' : 'unlocked') + '.'; }
  if (/\b(temperature|thermostat|degrees|warmer|cooler|heat|cool)\b/.test(text)) { var t = S.thermostat; if (/\bwhat|how (warm|cold|hot)\b/.test(text)) return 'The thermostat is set to ' + t.target + ' degrees.'; var n = (text.match(/\d+/) || [])[0]; if (/\bwarmer|up|raise|increase\b/.test(text)) t.target = Math.min(85, t.target + (n ? +n : 2)); else if (/\bcooler|down|lower|decrease\b/.test(text)) t.target = Math.max(55, t.target - (n ? +n : 2)); else if (n) t.target = Math.max(55, Math.min(85, +n)); t.on = true; render(); return 'Thermostat set to ' + t.target + ' degrees.'; }
  if (/\b(light|lights|lamp)\b/.test(text)) { var on = /\bon\b/.test(text) && !/\boff\b/.test(text); var room = findRoomByText(text); var targets2 = S.lights; if (room && room !== 'all') targets2 = S.lights.filter(function (l) { return l.room === room; }); else if (!/\b(all|every|everything|house)\b/.test(text) && !room) { var nl = S.lights.filter(function (l) { return text.indexOf(l.name.toLowerCase()) >= 0; }); if (nl.length) targets2 = nl; } targets2.forEach(function (l) { l.on = on; if (on && l.brightness < 5) l.brightness = 80; }); render(); var where = room && room !== 'all' ? (S.rooms.find(function (r) { return r.id === room; }) || {}).name : null; return (where ? where + ' lights' : targets2.length + ' lights') + ' turned ' + (on ? 'on' : 'off') + '.'; }
  var dev = S.devices.find(function (d) { return text.indexOf(d.name.toLowerCase()) >= 0; });
  if (dev && /\b(on|off|start|stop|turn|switch)\b/.test(text)) { var don = /\b(on|start)\b/.test(text) && !/\b(off|stop)\b/.test(text); dev.status = don ? 'on' : 'off'; render(); return dev.name + ' turned ' + (don ? 'on' : 'off') + '.'; }
  if (/^add /.test(text) || /\badd\b.*\b(shopping|list|cart|groceries)\b/.test(text)) { var item = text.replace(/.*\badd\b/, '').replace(/\bto\b.*$/, '').replace(/\b(the|my|shopping|list|cart)\b/g, '').trim(); if (item) { S.shopping.push({ id: ++S.nid, name: item.replace(/\b\w/g, function (c) { return c.toUpperCase(); }), qty: '1', checked: false, addedBy: S.userId, cat: 'Other' }); render(); return 'Added ' + item + ' to the shopping list.'; } }
  if (/\b(status|report|summary|what's up|whats up|home status)\b/.test(text)) { var lo = S.lights.filter(function (l) { return l.on; }).length; var ul = S.devices.filter(function (d) { return d.type === 'lock' && d.status !== 'locked'; }).length; return lo + ' lights on, ' + (ul === 0 ? 'all doors locked' : ul + ' door' + (ul > 1 ? 's' : '') + ' unlocked') + ', security ' + (S.securityArmed ? 'armed' : 'off') + ', and it is ' + S.thermostat.temp + ' degrees.'; }
  return "Sorry, I can't do that yet. Try \"turn on the lights\", \"lock the doors\", or \"good night\".";
}

var recog = null, listening = false;
function setMicState(active) { var b = document.getElementById('voice-btn'); if (b) b.classList.toggle('voice-active', active); }
export function handleVoice(text) { if (!text) return; showToast('“' + text + '”', 'info'); var reply = runVoice(text); speak(reply); setTimeout(function () { showToast(reply, reply.indexOf('Sorry') === 0 ? 'warning' : 'success'); }, 350); }
export function startListening() { var SR = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SR) { showToast('Voice input not supported here — opening voice panel', 'warning'); openVoicePanel(); return; } if (listening) { try { recog.stop(); } catch (e) {} return; } recog = new SR(); recog.lang = 'en-US'; recog.interimResults = false; recog.maxAlternatives = 1; recog.onstart = function () { listening = true; setMicState(true); }; recog.onerror = function (e) { listening = false; setMicState(false); if (e.error === 'not-allowed') showToast('Microphone permission denied', 'error'); else if (e.error !== 'no-speech' && e.error !== 'aborted') showToast('Voice error: ' + e.error, 'error'); }; recog.onend = function () { listening = false; setMicState(false); }; recog.onresult = function (e) { handleVoice(e.results[0][0].transcript); }; try { recog.start(); showToast('Listening… speak now', 'info'); } catch (e) { listening = false; setMicState(false); } }
export function toggleAssistant(key) { S.assistants[key] = !S.assistants[key]; persist(); openVoicePanel(); showToast((S.assistants[key] ? 'Linked ' : 'Unlinked ') + key.charAt(0).toUpperCase() + key.slice(1), S.assistants[key] ? 'success' : 'info'); }
export function copyText(t, label) { try { navigator.clipboard.writeText(t); showToast((label || 'Copied') + ' copied', 'success'); } catch (e) { showToast('Copy failed', 'error'); } }
// Read the JWT from storage at click time (avoids keeping it on a global).
export function copyToken() { copyText(localStorage.getItem('homepal-token') || '', 'Token'); }
export function runTestVoice() { var v = val('voice-test').trim(); if (!v) { showToast('Type a command', 'warning'); return; } handleVoice(v); }
export function openVoicePanel() {
  var a = S.assistants || {}; var origin = (location.origin && location.origin.indexOf('http') === 0) ? location.origin : 'http://localhost:3000'; var endpoint = origin + '/api/voice';
  var cards = [{ k: 'alexa', n: 'Amazon Alexa', i: 'fa-brands fa-amazon', c: '#00CAFF' }, { k: 'google', n: 'Google Assistant', i: 'fa-brands fa-google', c: '#EA4335' }, { k: 'siri', n: 'Apple Siri', i: 'fa-brands fa-apple', c: '#D1D5DB' }, { k: 'homekit', n: 'Apple HomeKit', i: 'fa-solid fa-house-lock', c: '#10B981' }].map(function (x) { var on = !!a[x.k]; return '<div class="p-3 rounded-xl border flex items-center gap-3" style="border-color:' + (on ? x.c : 'var(--border)') + ';background:' + (on ? x.c + '12' : 'var(--bg2)') + '"><div class="w-9 h-9 rounded-lg flex items-center justify-center" style="background:' + x.c + '1f;color:' + x.c + '"><i class="' + x.i + '"></i></div><div class="flex-1 min-w-0"><div class="text-sm font-semibold">' + x.n + '</div><div class="text-[10px] text-[var(--muted)]">' + (on ? 'Linked' : 'Not linked') + '</div></div><div class="toggle ' + (on ? 'on' : '') + '" style="width:40px;height:22px" onclick="toggleAssistant(\'' + x.k + '\')" aria-label="Link ' + x.n + '"></div></div>'; }).join('');
  var phrases = ['Turn on the living room lights', 'Lock the doors', 'Set the temperature to 70', 'Activate good night', 'Arm the security system', 'Add milk to the shopping list'].map(function (p) { return '<button class="btn btn-sm btn-ghost" style="font-weight:500" onclick="document.getElementById(\'voice-test\').value=\'' + p.replace(/'/g, "\\'") + '\';runTestVoice()">' + p + '</button>'; }).join('');
  showModal('<div class="p-5"><div class="flex items-center justify-between mb-1"><h3 class="font-bold flex items-center gap-2"><i class="fa-solid fa-microphone-lines text-[var(--accent)]"></i>Voice &amp; Assistants</h3><button class="text-[var(--muted)] hover:text-[var(--fg)]" onclick="hideModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><p class="text-xs text-[var(--muted)] mb-4">Control your home by voice in-app, and connect external assistants through the secure command endpoint.</p><div class="grid grid-cols-1 sm:grid-cols-2 gap-2.5 mb-4">' + cards + '</div><div class="mb-4"><label>Try a command</label><div class="flex gap-2"><input class="input flex-1" id="voice-test" placeholder="e.g. turn on the kitchen lights" onkeydown="if(event.key===\'Enter\')runTestVoice()"><button class="btn btn-primary" onclick="runTestVoice()">Run</button><button class="btn btn-secondary" title="Speak" onclick="startListening()" aria-label="Speak"><i class="fa-solid fa-microphone"></i></button></div></div><div class="mb-4"><label>Example phrases</label><div class="flex flex-wrap gap-2">' + phrases + '</div></div><div class="p-3 rounded-xl bg-[var(--bg2)] border border-[var(--border)]"><div class="flex items-center justify-between mb-1"><span class="text-xs font-semibold"><i class="fa-solid fa-link mr-1 text-[var(--cyan)]"></i>Command endpoint</span><button class="text-[10px] text-[var(--accent)] hover:underline" onclick="copyText(\'' + endpoint + '\',\'Endpoint\')">Copy</button></div><code class="text-[11px] text-[var(--muted)] break-all">POST ' + endpoint + '</code><p class="text-[10px] text-[var(--muted)] mt-2 leading-relaxed">For Siri: create a Shortcut → <b>Get Contents of URL</b> (POST, JSON body <code>{"command":"&lt;Dictated Text&gt;"}</code>, header <code>Authorization: Bearer &lt;token&gt;</code>). For Alexa/Google, point your skill’s webhook at this URL. <button class="text-[var(--accent)] hover:underline" onclick="copyToken()">Copy access token</button></p></div></div>');
}
